/* ============================================================
 * model_int8_weights.h — Auto-generated by export_weights.py
 * Model: facebook/mms-tts-por (VITS, 36.3M params)
 * DO NOT EDIT MANUALLY — regenerate with:
 *   python export_weights.py --input model.safetensors \
 *       --output model.vtsm --header model_int8_weights.h --int8
 * ============================================================ */

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <stdint.h>
#include <stddef.h>

/* ── File header ── */
#define WTS_MAGIC            0x4D535456u  /* 'V','T','S','M' LE */
#define WTS_VERSION          2
#define WTS_VOCAB_SIZE       43
#define WTS_HIDDEN_SIZE      192
#define WTS_FILE_HEADER_SIZE 48
#define WTS_TOTAL_DATA_BYTES 56311904
#define WTS_QDATA_SIZE         14317792  /* int8 weight elements */
#define WTS_N_SCALES           9633  /* per-channel scales (float32) */
/* int8 qdata offset: WTS_FILE_HEADER_SIZE + WTS_TOTAL_DATA_BYTES */
/* scales offset:     WTS_FILE_HEADER_SIZE + WTS_TOTAL_DATA_BYTES + WTS_QDATA_SIZE */

/* ── Model dimensions ── */
#define WTS_NUM_HEADS        2
#define WTS_HEAD_DIM         96
#define WTS_NUM_LAYERS       6
#define WTS_REL_SIZE         9
#define WTS_FFN_DIM          768
#define WTS_FFN_KERNEL       3
#define WTS_HALF_FLOW        96
#define WTS_WAVE_KERNEL      5
#define WTS_NUM_WAVE         4
#define WTS_NUM_PRIOR_FLOWS  4
#define WTS_DP_BINS          10
#define WTS_DP_KERNEL        3
#define WTS_DP_NUM_FLOWS     4
#define WTS_DP_CHANNELS      2
#define WTS_DP_DDS_LAYERS    3
#define WTS_DP_PROJ_OUT      29
#define WTS_HIFI_INIT_CH     512
#define WTS_NUM_UP           4
#define WTS_RF_DILS          3
#define WTS_NUM_RESBLOCKS    12

/* ── Size constants (float32 element counts) ── */
#define WTS_EMBED_W_SIZE             8256

#define WTS_ENC_ATTN_W_SIZE          36864
#define WTS_ENC_ATTN_B_SIZE          192
#define WTS_ENC_REL_SIZE             864
#define WTS_ENC_FFN1_W_SIZE          442368
#define WTS_ENC_FFN1_B_SIZE          768
#define WTS_ENC_FFN2_W_SIZE          442368
#define WTS_ENC_FFN2_B_SIZE          192
#define WTS_ENC_LN_SIZE              192
#define WTS_ENC_LAYER_SIZE           1036416  /* per layer, all tensors */

#define WTS_ENC_PROJ_W_SIZE          73728
#define WTS_ENC_PROJ_B_SIZE          384

#define WTS_DP_CONV_PRE_W_SIZE       36864
#define WTS_DP_CONV_PRE_B_SIZE       192
#define WTS_DP_DDS_DW_W_SIZE         576
#define WTS_DP_DDS_DW_B_SIZE         192
#define WTS_DP_DDS_PW_W_SIZE         36864
#define WTS_DP_DDS_PW_B_SIZE         192
#define WTS_DP_DDS_NORM_SIZE         192
#define WTS_DP_DDS_LAYER_SIZE        38592  /* per DDS layer */
#define WTS_DP_DDS_SIZE              115776  /* full DDS block */
#define WTS_DP_CONV_PROJ_W_SIZE      36864
#define WTS_DP_CONV_PROJ_B_SIZE      192
#define WTS_DP_EA_SIZE               2  /* translate or log_scale */
#define WTS_DP_CF_PRE_W_SIZE         192
#define WTS_DP_CF_PRE_B_SIZE         192
#define WTS_DP_CF_PROJ_W_SIZE        5568
#define WTS_DP_CF_PROJ_B_SIZE        29

#define WTS_FLOW_PRE_W_SIZE          18432
#define WTS_FLOW_PRE_B_SIZE          192
#define WTS_FLOW_WN_IN_W_SIZE        368640
#define WTS_FLOW_WN_IN_B_SIZE        384
#define WTS_FLOW_WN_RS_W_SIZE        73728  /* layers 0-2 */
#define WTS_FLOW_WN_RS_W_SIZE_LAST   36864  /* layer 3 */
#define WTS_FLOW_WN_RS_B_SIZE        384
#define WTS_FLOW_WN_RS_B_SIZE_LAST   192
#define WTS_FLOW_POST_W_SIZE         18432
#define WTS_FLOW_POST_B_SIZE         96

#define WTS_DEC_PRE_W_SIZE           688128
#define WTS_DEC_PRE_B_SIZE           512
#define WTS_DEC_UP0_W_SIZE           2097152
#define WTS_DEC_UP0_B_SIZE           256
#define WTS_DEC_UP1_W_SIZE           524288
#define WTS_DEC_UP1_B_SIZE           128
#define WTS_DEC_UP2_W_SIZE           32768
#define WTS_DEC_UP2_B_SIZE           64
#define WTS_DEC_UP3_W_SIZE           8192
#define WTS_DEC_UP3_B_SIZE           32
#define WTS_DEC_RB0_0_W_SIZE        196608
#define WTS_DEC_RB0_0_B_SIZE        256
#define WTS_DEC_RB0_1_W_SIZE        458752
#define WTS_DEC_RB0_1_B_SIZE        256
#define WTS_DEC_RB0_2_W_SIZE        720896
#define WTS_DEC_RB0_2_B_SIZE        256
#define WTS_DEC_RB1_0_W_SIZE        49152
#define WTS_DEC_RB1_0_B_SIZE        128
#define WTS_DEC_RB1_1_W_SIZE        114688
#define WTS_DEC_RB1_1_B_SIZE        128
#define WTS_DEC_RB1_2_W_SIZE        180224
#define WTS_DEC_RB1_2_B_SIZE        128
#define WTS_DEC_RB2_0_W_SIZE        12288
#define WTS_DEC_RB2_0_B_SIZE        64
#define WTS_DEC_RB2_1_W_SIZE        28672
#define WTS_DEC_RB2_1_B_SIZE        64
#define WTS_DEC_RB2_2_W_SIZE        45056
#define WTS_DEC_RB2_2_B_SIZE        64
#define WTS_DEC_RB3_0_W_SIZE        3072
#define WTS_DEC_RB3_0_B_SIZE        32
#define WTS_DEC_RB3_1_W_SIZE        7168
#define WTS_DEC_RB3_1_B_SIZE        32
#define WTS_DEC_RB3_2_W_SIZE        11264
#define WTS_DEC_RB3_2_B_SIZE        32
#define WTS_DEC_POST_W_SIZE          224


/* ── Tensor descriptor ── */
typedef struct {
    const char *name;       /* tensor name */
    uint32_t     ndim;       /* number of dimensions */
    uint32_t     shape[4];   /* dimensions (0 if ndim < 4) */
    uint32_t     n_elements; /* total float32 count */
    uint64_t     offset;     /* byte offset in .vtsm file */
    uint64_t     size_bytes; /* n_elements * 4 */
} WtsTensor;

/* ── Section descriptor ── */
typedef struct {
    const char *name;             /* section name */
    const WtsTensor *tensors;     /* array of tensor descriptors */
    uint32_t     n_tensors;       /* number of tensors */
    uint32_t     n_elements;      /* total floats in section */
    uint64_t     offset;          /* byte offset of first tensor */
} WtsSection;

/* ── Flat tensor layout table (410 entries) ── */
static const WtsTensor wts_tensors[] = {
    { "embed_tokens.weight", 2, {43, 192, 0, 0}, 8256, 48, 33024 },
    { "enc.0.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 33072, 147456 },
    { "enc.0.q_proj.bias", 1, {192, 0, 0, 0}, 192, 180528, 768 },
    { "enc.0.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 181296, 147456 },
    { "enc.0.k_proj.bias", 1, {192, 0, 0, 0}, 192, 328752, 768 },
    { "enc.0.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 329520, 147456 },
    { "enc.0.v_proj.bias", 1, {192, 0, 0, 0}, 192, 476976, 768 },
    { "enc.0.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 477744, 147456 },
    { "enc.0.out_proj.bias", 1, {192, 0, 0, 0}, 192, 625200, 768 },
    { "enc.0.emb_rel_k", 2, {9, 96, 0, 0}, 864, 625968, 3456 },
    { "enc.0.emb_rel_v", 2, {9, 96, 0, 0}, 864, 629424, 3456 },
    { "enc.0.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 632880, 1769472 },
    { "enc.0.ffn1.bias", 1, {768, 0, 0, 0}, 768, 2402352, 3072 },
    { "enc.0.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 2405424, 1769472 },
    { "enc.0.ffn2.bias", 1, {192, 0, 0, 0}, 192, 4174896, 768 },
    { "enc.0.ln1.weight", 1, {192, 0, 0, 0}, 192, 4175664, 768 },
    { "enc.0.ln1.bias", 1, {192, 0, 0, 0}, 192, 4176432, 768 },
    { "enc.0.ln2.weight", 1, {192, 0, 0, 0}, 192, 4177200, 768 },
    { "enc.0.ln2.bias", 1, {192, 0, 0, 0}, 192, 4177968, 768 },
    { "enc.1.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 4178736, 147456 },
    { "enc.1.q_proj.bias", 1, {192, 0, 0, 0}, 192, 4326192, 768 },
    { "enc.1.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 4326960, 147456 },
    { "enc.1.k_proj.bias", 1, {192, 0, 0, 0}, 192, 4474416, 768 },
    { "enc.1.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 4475184, 147456 },
    { "enc.1.v_proj.bias", 1, {192, 0, 0, 0}, 192, 4622640, 768 },
    { "enc.1.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 4623408, 147456 },
    { "enc.1.out_proj.bias", 1, {192, 0, 0, 0}, 192, 4770864, 768 },
    { "enc.1.emb_rel_k", 2, {9, 96, 0, 0}, 864, 4771632, 3456 },
    { "enc.1.emb_rel_v", 2, {9, 96, 0, 0}, 864, 4775088, 3456 },
    { "enc.1.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 4778544, 1769472 },
    { "enc.1.ffn1.bias", 1, {768, 0, 0, 0}, 768, 6548016, 3072 },
    { "enc.1.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 6551088, 1769472 },
    { "enc.1.ffn2.bias", 1, {192, 0, 0, 0}, 192, 8320560, 768 },
    { "enc.1.ln1.weight", 1, {192, 0, 0, 0}, 192, 8321328, 768 },
    { "enc.1.ln1.bias", 1, {192, 0, 0, 0}, 192, 8322096, 768 },
    { "enc.1.ln2.weight", 1, {192, 0, 0, 0}, 192, 8322864, 768 },
    { "enc.1.ln2.bias", 1, {192, 0, 0, 0}, 192, 8323632, 768 },
    { "enc.2.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 8324400, 147456 },
    { "enc.2.q_proj.bias", 1, {192, 0, 0, 0}, 192, 8471856, 768 },
    { "enc.2.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 8472624, 147456 },
    { "enc.2.k_proj.bias", 1, {192, 0, 0, 0}, 192, 8620080, 768 },
    { "enc.2.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 8620848, 147456 },
    { "enc.2.v_proj.bias", 1, {192, 0, 0, 0}, 192, 8768304, 768 },
    { "enc.2.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 8769072, 147456 },
    { "enc.2.out_proj.bias", 1, {192, 0, 0, 0}, 192, 8916528, 768 },
    { "enc.2.emb_rel_k", 2, {9, 96, 0, 0}, 864, 8917296, 3456 },
    { "enc.2.emb_rel_v", 2, {9, 96, 0, 0}, 864, 8920752, 3456 },
    { "enc.2.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 8924208, 1769472 },
    { "enc.2.ffn1.bias", 1, {768, 0, 0, 0}, 768, 10693680, 3072 },
    { "enc.2.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 10696752, 1769472 },
    { "enc.2.ffn2.bias", 1, {192, 0, 0, 0}, 192, 12466224, 768 },
    { "enc.2.ln1.weight", 1, {192, 0, 0, 0}, 192, 12466992, 768 },
    { "enc.2.ln1.bias", 1, {192, 0, 0, 0}, 192, 12467760, 768 },
    { "enc.2.ln2.weight", 1, {192, 0, 0, 0}, 192, 12468528, 768 },
    { "enc.2.ln2.bias", 1, {192, 0, 0, 0}, 192, 12469296, 768 },
    { "enc.3.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 12470064, 147456 },
    { "enc.3.q_proj.bias", 1, {192, 0, 0, 0}, 192, 12617520, 768 },
    { "enc.3.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 12618288, 147456 },
    { "enc.3.k_proj.bias", 1, {192, 0, 0, 0}, 192, 12765744, 768 },
    { "enc.3.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 12766512, 147456 },
    { "enc.3.v_proj.bias", 1, {192, 0, 0, 0}, 192, 12913968, 768 },
    { "enc.3.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 12914736, 147456 },
    { "enc.3.out_proj.bias", 1, {192, 0, 0, 0}, 192, 13062192, 768 },
    { "enc.3.emb_rel_k", 2, {9, 96, 0, 0}, 864, 13062960, 3456 },
    { "enc.3.emb_rel_v", 2, {9, 96, 0, 0}, 864, 13066416, 3456 },
    { "enc.3.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 13069872, 1769472 },
    { "enc.3.ffn1.bias", 1, {768, 0, 0, 0}, 768, 14839344, 3072 },
    { "enc.3.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 14842416, 1769472 },
    { "enc.3.ffn2.bias", 1, {192, 0, 0, 0}, 192, 16611888, 768 },
    { "enc.3.ln1.weight", 1, {192, 0, 0, 0}, 192, 16612656, 768 },
    { "enc.3.ln1.bias", 1, {192, 0, 0, 0}, 192, 16613424, 768 },
    { "enc.3.ln2.weight", 1, {192, 0, 0, 0}, 192, 16614192, 768 },
    { "enc.3.ln2.bias", 1, {192, 0, 0, 0}, 192, 16614960, 768 },
    { "enc.4.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 16615728, 147456 },
    { "enc.4.q_proj.bias", 1, {192, 0, 0, 0}, 192, 16763184, 768 },
    { "enc.4.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 16763952, 147456 },
    { "enc.4.k_proj.bias", 1, {192, 0, 0, 0}, 192, 16911408, 768 },
    { "enc.4.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 16912176, 147456 },
    { "enc.4.v_proj.bias", 1, {192, 0, 0, 0}, 192, 17059632, 768 },
    { "enc.4.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 17060400, 147456 },
    { "enc.4.out_proj.bias", 1, {192, 0, 0, 0}, 192, 17207856, 768 },
    { "enc.4.emb_rel_k", 2, {9, 96, 0, 0}, 864, 17208624, 3456 },
    { "enc.4.emb_rel_v", 2, {9, 96, 0, 0}, 864, 17212080, 3456 },
    { "enc.4.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 17215536, 1769472 },
    { "enc.4.ffn1.bias", 1, {768, 0, 0, 0}, 768, 18985008, 3072 },
    { "enc.4.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 18988080, 1769472 },
    { "enc.4.ffn2.bias", 1, {192, 0, 0, 0}, 192, 20757552, 768 },
    { "enc.4.ln1.weight", 1, {192, 0, 0, 0}, 192, 20758320, 768 },
    { "enc.4.ln1.bias", 1, {192, 0, 0, 0}, 192, 20759088, 768 },
    { "enc.4.ln2.weight", 1, {192, 0, 0, 0}, 192, 20759856, 768 },
    { "enc.4.ln2.bias", 1, {192, 0, 0, 0}, 192, 20760624, 768 },
    { "enc.5.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 20761392, 147456 },
    { "enc.5.q_proj.bias", 1, {192, 0, 0, 0}, 192, 20908848, 768 },
    { "enc.5.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 20909616, 147456 },
    { "enc.5.k_proj.bias", 1, {192, 0, 0, 0}, 192, 21057072, 768 },
    { "enc.5.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 21057840, 147456 },
    { "enc.5.v_proj.bias", 1, {192, 0, 0, 0}, 192, 21205296, 768 },
    { "enc.5.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 21206064, 147456 },
    { "enc.5.out_proj.bias", 1, {192, 0, 0, 0}, 192, 21353520, 768 },
    { "enc.5.emb_rel_k", 2, {9, 96, 0, 0}, 864, 21354288, 3456 },
    { "enc.5.emb_rel_v", 2, {9, 96, 0, 0}, 864, 21357744, 3456 },
    { "enc.5.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 21361200, 1769472 },
    { "enc.5.ffn1.bias", 1, {768, 0, 0, 0}, 768, 23130672, 3072 },
    { "enc.5.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 23133744, 1769472 },
    { "enc.5.ffn2.bias", 1, {192, 0, 0, 0}, 192, 24903216, 768 },
    { "enc.5.ln1.weight", 1, {192, 0, 0, 0}, 192, 24903984, 768 },
    { "enc.5.ln1.bias", 1, {192, 0, 0, 0}, 192, 24904752, 768 },
    { "enc.5.ln2.weight", 1, {192, 0, 0, 0}, 192, 24905520, 768 },
    { "enc.5.ln2.bias", 1, {192, 0, 0, 0}, 192, 24906288, 768 },
    { "enc.proj.weight", 3, {384, 192, 1, 0}, 73728, 24907056, 294912 },
    { "enc.proj.bias", 1, {384, 0, 0, 0}, 384, 25201968, 1536 },
    { "dp.conv_pre.weight", 3, {192, 192, 1, 0}, 36864, 25203504, 147456 },
    { "dp.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 25350960, 768 },
    { "dp.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 25351728, 2304 },
    { "dp.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 25354032, 768 },
    { "dp.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 25354800, 147456 },
    { "dp.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 25502256, 768 },
    { "dp.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 25503024, 768 },
    { "dp.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 25503792, 768 },
    { "dp.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 25504560, 768 },
    { "dp.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 25505328, 768 },
    { "dp.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 25506096, 2304 },
    { "dp.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 25508400, 768 },
    { "dp.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 25509168, 147456 },
    { "dp.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 25656624, 768 },
    { "dp.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 25657392, 768 },
    { "dp.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 25658160, 768 },
    { "dp.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 25658928, 768 },
    { "dp.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 25659696, 768 },
    { "dp.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 25660464, 2304 },
    { "dp.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 25662768, 768 },
    { "dp.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 25663536, 147456 },
    { "dp.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 25810992, 768 },
    { "dp.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 25811760, 768 },
    { "dp.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 25812528, 768 },
    { "dp.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 25813296, 768 },
    { "dp.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 25814064, 768 },
    { "dp.conv_proj.weight", 3, {192, 192, 1, 0}, 36864, 25814832, 147456 },
    { "dp.conv_proj.bias", 1, {192, 0, 0, 0}, 192, 25962288, 768 },
    { "dp.flow0.translate", 1, {2, 0, 0, 0}, 2, 25963056, 8 },
    { "dp.flow0.log_scale", 1, {2, 0, 0, 0}, 2, 25963064, 8 },
    { "dp.flow1.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 25963072, 768 },
    { "dp.flow1.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 25963840, 768 },
    { "dp.flow1.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 25964608, 2304 },
    { "dp.flow1.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 25966912, 768 },
    { "dp.flow1.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 25967680, 147456 },
    { "dp.flow1.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 26115136, 768 },
    { "dp.flow1.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 26115904, 768 },
    { "dp.flow1.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 26116672, 768 },
    { "dp.flow1.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 26117440, 768 },
    { "dp.flow1.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 26118208, 768 },
    { "dp.flow1.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 26118976, 2304 },
    { "dp.flow1.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 26121280, 768 },
    { "dp.flow1.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 26122048, 147456 },
    { "dp.flow1.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 26269504, 768 },
    { "dp.flow1.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 26270272, 768 },
    { "dp.flow1.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 26271040, 768 },
    { "dp.flow1.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 26271808, 768 },
    { "dp.flow1.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 26272576, 768 },
    { "dp.flow1.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 26273344, 2304 },
    { "dp.flow1.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 26275648, 768 },
    { "dp.flow1.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 26276416, 147456 },
    { "dp.flow1.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 26423872, 768 },
    { "dp.flow1.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 26424640, 768 },
    { "dp.flow1.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 26425408, 768 },
    { "dp.flow1.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 26426176, 768 },
    { "dp.flow1.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 26426944, 768 },
    { "dp.flow1.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 26427712, 22272 },
    { "dp.flow1.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 26449984, 116 },
    { "dp.flow2.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 26450100, 768 },
    { "dp.flow2.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 26450868, 768 },
    { "dp.flow2.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 26451636, 2304 },
    { "dp.flow2.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 26453940, 768 },
    { "dp.flow2.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 26454708, 147456 },
    { "dp.flow2.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 26602164, 768 },
    { "dp.flow2.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 26602932, 768 },
    { "dp.flow2.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 26603700, 768 },
    { "dp.flow2.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 26604468, 768 },
    { "dp.flow2.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 26605236, 768 },
    { "dp.flow2.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 26606004, 2304 },
    { "dp.flow2.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 26608308, 768 },
    { "dp.flow2.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 26609076, 147456 },
    { "dp.flow2.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 26756532, 768 },
    { "dp.flow2.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 26757300, 768 },
    { "dp.flow2.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 26758068, 768 },
    { "dp.flow2.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 26758836, 768 },
    { "dp.flow2.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 26759604, 768 },
    { "dp.flow2.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 26760372, 2304 },
    { "dp.flow2.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 26762676, 768 },
    { "dp.flow2.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 26763444, 147456 },
    { "dp.flow2.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 26910900, 768 },
    { "dp.flow2.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 26911668, 768 },
    { "dp.flow2.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 26912436, 768 },
    { "dp.flow2.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 26913204, 768 },
    { "dp.flow2.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 26913972, 768 },
    { "dp.flow2.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 26914740, 22272 },
    { "dp.flow2.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 26937012, 116 },
    { "dp.flow3.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 26937128, 768 },
    { "dp.flow3.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 26937896, 768 },
    { "dp.flow3.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 26938664, 2304 },
    { "dp.flow3.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 26940968, 768 },
    { "dp.flow3.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 26941736, 147456 },
    { "dp.flow3.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 27089192, 768 },
    { "dp.flow3.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 27089960, 768 },
    { "dp.flow3.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 27090728, 768 },
    { "dp.flow3.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 27091496, 768 },
    { "dp.flow3.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 27092264, 768 },
    { "dp.flow3.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 27093032, 2304 },
    { "dp.flow3.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 27095336, 768 },
    { "dp.flow3.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 27096104, 147456 },
    { "dp.flow3.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 27243560, 768 },
    { "dp.flow3.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 27244328, 768 },
    { "dp.flow3.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 27245096, 768 },
    { "dp.flow3.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 27245864, 768 },
    { "dp.flow3.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 27246632, 768 },
    { "dp.flow3.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 27247400, 2304 },
    { "dp.flow3.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 27249704, 768 },
    { "dp.flow3.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 27250472, 147456 },
    { "dp.flow3.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 27397928, 768 },
    { "dp.flow3.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 27398696, 768 },
    { "dp.flow3.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 27399464, 768 },
    { "dp.flow3.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 27400232, 768 },
    { "dp.flow3.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 27401000, 768 },
    { "dp.flow3.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 27401768, 22272 },
    { "dp.flow3.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 27424040, 116 },
    { "dp.flow4.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 27424156, 768 },
    { "dp.flow4.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 27424924, 768 },
    { "dp.flow4.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 27425692, 2304 },
    { "dp.flow4.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 27427996, 768 },
    { "dp.flow4.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 27428764, 147456 },
    { "dp.flow4.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 27576220, 768 },
    { "dp.flow4.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 27576988, 768 },
    { "dp.flow4.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 27577756, 768 },
    { "dp.flow4.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 27578524, 768 },
    { "dp.flow4.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 27579292, 768 },
    { "dp.flow4.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 27580060, 2304 },
    { "dp.flow4.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 27582364, 768 },
    { "dp.flow4.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 27583132, 147456 },
    { "dp.flow4.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 27730588, 768 },
    { "dp.flow4.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 27731356, 768 },
    { "dp.flow4.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 27732124, 768 },
    { "dp.flow4.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 27732892, 768 },
    { "dp.flow4.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 27733660, 768 },
    { "dp.flow4.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 27734428, 2304 },
    { "dp.flow4.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 27736732, 768 },
    { "dp.flow4.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 27737500, 147456 },
    { "dp.flow4.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 27884956, 768 },
    { "dp.flow4.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 27885724, 768 },
    { "dp.flow4.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 27886492, 768 },
    { "dp.flow4.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 27887260, 768 },
    { "dp.flow4.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 27888028, 768 },
    { "dp.flow4.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 27888796, 22272 },
    { "dp.flow4.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 27911068, 116 },
    { "flow.0.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 27911184, 73728 },
    { "flow.0.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 27984912, 768 },
    { "flow.0.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 27985680, 1474560 },
    { "flow.0.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 29460240, 1536 },
    { "flow.0.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 29461776, 294912 },
    { "flow.0.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 29756688, 1536 },
    { "flow.0.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 29758224, 1474560 },
    { "flow.0.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 31232784, 1536 },
    { "flow.0.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 31234320, 294912 },
    { "flow.0.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 31529232, 1536 },
    { "flow.0.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 31530768, 1474560 },
    { "flow.0.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 33005328, 1536 },
    { "flow.0.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 33006864, 294912 },
    { "flow.0.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 33301776, 1536 },
    { "flow.0.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 33303312, 1474560 },
    { "flow.0.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 34777872, 1536 },
    { "flow.0.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 34779408, 147456 },
    { "flow.0.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 34926864, 768 },
    { "flow.0.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 34927632, 73728 },
    { "flow.0.conv_post.bias", 1, {96, 0, 0, 0}, 96, 35001360, 384 },
    { "flow.1.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 35001744, 73728 },
    { "flow.1.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 35075472, 768 },
    { "flow.1.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 35076240, 1474560 },
    { "flow.1.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 36550800, 1536 },
    { "flow.1.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 36552336, 294912 },
    { "flow.1.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 36847248, 1536 },
    { "flow.1.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 36848784, 1474560 },
    { "flow.1.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 38323344, 1536 },
    { "flow.1.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 38324880, 294912 },
    { "flow.1.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 38619792, 1536 },
    { "flow.1.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 38621328, 1474560 },
    { "flow.1.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 40095888, 1536 },
    { "flow.1.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 40097424, 294912 },
    { "flow.1.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 40392336, 1536 },
    { "flow.1.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 40393872, 1474560 },
    { "flow.1.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 41868432, 1536 },
    { "flow.1.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 41869968, 147456 },
    { "flow.1.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 42017424, 768 },
    { "flow.1.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 42018192, 73728 },
    { "flow.1.conv_post.bias", 1, {96, 0, 0, 0}, 96, 42091920, 384 },
    { "flow.2.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 42092304, 73728 },
    { "flow.2.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 42166032, 768 },
    { "flow.2.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 42166800, 1474560 },
    { "flow.2.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 43641360, 1536 },
    { "flow.2.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 43642896, 294912 },
    { "flow.2.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 43937808, 1536 },
    { "flow.2.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 43939344, 1474560 },
    { "flow.2.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 45413904, 1536 },
    { "flow.2.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 45415440, 294912 },
    { "flow.2.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 45710352, 1536 },
    { "flow.2.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 45711888, 1474560 },
    { "flow.2.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 47186448, 1536 },
    { "flow.2.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 47187984, 294912 },
    { "flow.2.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 47482896, 1536 },
    { "flow.2.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 47484432, 1474560 },
    { "flow.2.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 48958992, 1536 },
    { "flow.2.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 48960528, 147456 },
    { "flow.2.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 49107984, 768 },
    { "flow.2.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 49108752, 73728 },
    { "flow.2.conv_post.bias", 1, {96, 0, 0, 0}, 96, 49182480, 384 },
    { "flow.3.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 49182864, 73728 },
    { "flow.3.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 49256592, 768 },
    { "flow.3.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 49257360, 1474560 },
    { "flow.3.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 50731920, 1536 },
    { "flow.3.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 50733456, 294912 },
    { "flow.3.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 51028368, 1536 },
    { "flow.3.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 51029904, 1474560 },
    { "flow.3.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 52504464, 1536 },
    { "flow.3.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 52506000, 294912 },
    { "flow.3.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 52800912, 1536 },
    { "flow.3.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 52802448, 1474560 },
    { "flow.3.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 54277008, 1536 },
    { "flow.3.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 54278544, 294912 },
    { "flow.3.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 54573456, 1536 },
    { "flow.3.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 54574992, 1474560 },
    { "flow.3.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 56049552, 1536 },
    { "flow.3.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 56051088, 147456 },
    { "flow.3.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 56198544, 768 },
    { "flow.3.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 56199312, 73728 },
    { "flow.3.conv_post.bias", 1, {96, 0, 0, 0}, 96, 56273040, 384 },
    { "dec.conv_pre.bias", 1, {512, 0, 0, 0}, 512, 56273424, 2048 },
    { "dec.up.0.bias", 1, {256, 0, 0, 0}, 256, 56275472, 1024 },
    { "dec.up.1.bias", 1, {128, 0, 0, 0}, 128, 56276496, 512 },
    { "dec.up.2.bias", 1, {64, 0, 0, 0}, 64, 56277008, 256 },
    { "dec.up.3.bias", 1, {32, 0, 0, 0}, 32, 56277264, 128 },
    { "dec.rb.0.c1.0.bias", 1, {256, 0, 0, 0}, 256, 56277392, 1024 },
    { "dec.rb.0.c2.0.bias", 1, {256, 0, 0, 0}, 256, 56278416, 1024 },
    { "dec.rb.0.c1.1.bias", 1, {256, 0, 0, 0}, 256, 56279440, 1024 },
    { "dec.rb.0.c2.1.bias", 1, {256, 0, 0, 0}, 256, 56280464, 1024 },
    { "dec.rb.0.c1.2.bias", 1, {256, 0, 0, 0}, 256, 56281488, 1024 },
    { "dec.rb.0.c2.2.bias", 1, {256, 0, 0, 0}, 256, 56282512, 1024 },
    { "dec.rb.1.c1.0.bias", 1, {256, 0, 0, 0}, 256, 56283536, 1024 },
    { "dec.rb.1.c2.0.bias", 1, {256, 0, 0, 0}, 256, 56284560, 1024 },
    { "dec.rb.1.c1.1.bias", 1, {256, 0, 0, 0}, 256, 56285584, 1024 },
    { "dec.rb.1.c2.1.bias", 1, {256, 0, 0, 0}, 256, 56286608, 1024 },
    { "dec.rb.1.c1.2.bias", 1, {256, 0, 0, 0}, 256, 56287632, 1024 },
    { "dec.rb.1.c2.2.bias", 1, {256, 0, 0, 0}, 256, 56288656, 1024 },
    { "dec.rb.2.c1.0.bias", 1, {256, 0, 0, 0}, 256, 56289680, 1024 },
    { "dec.rb.2.c2.0.bias", 1, {256, 0, 0, 0}, 256, 56290704, 1024 },
    { "dec.rb.2.c1.1.bias", 1, {256, 0, 0, 0}, 256, 56291728, 1024 },
    { "dec.rb.2.c2.1.bias", 1, {256, 0, 0, 0}, 256, 56292752, 1024 },
    { "dec.rb.2.c1.2.bias", 1, {256, 0, 0, 0}, 256, 56293776, 1024 },
    { "dec.rb.2.c2.2.bias", 1, {256, 0, 0, 0}, 256, 56294800, 1024 },
    { "dec.rb.3.c1.0.bias", 1, {128, 0, 0, 0}, 128, 56295824, 512 },
    { "dec.rb.3.c2.0.bias", 1, {128, 0, 0, 0}, 128, 56296336, 512 },
    { "dec.rb.3.c1.1.bias", 1, {128, 0, 0, 0}, 128, 56296848, 512 },
    { "dec.rb.3.c2.1.bias", 1, {128, 0, 0, 0}, 128, 56297360, 512 },
    { "dec.rb.3.c1.2.bias", 1, {128, 0, 0, 0}, 128, 56297872, 512 },
    { "dec.rb.3.c2.2.bias", 1, {128, 0, 0, 0}, 128, 56298384, 512 },
    { "dec.rb.4.c1.0.bias", 1, {128, 0, 0, 0}, 128, 56298896, 512 },
    { "dec.rb.4.c2.0.bias", 1, {128, 0, 0, 0}, 128, 56299408, 512 },
    { "dec.rb.4.c1.1.bias", 1, {128, 0, 0, 0}, 128, 56299920, 512 },
    { "dec.rb.4.c2.1.bias", 1, {128, 0, 0, 0}, 128, 56300432, 512 },
    { "dec.rb.4.c1.2.bias", 1, {128, 0, 0, 0}, 128, 56300944, 512 },
    { "dec.rb.4.c2.2.bias", 1, {128, 0, 0, 0}, 128, 56301456, 512 },
    { "dec.rb.5.c1.0.bias", 1, {128, 0, 0, 0}, 128, 56301968, 512 },
    { "dec.rb.5.c2.0.bias", 1, {128, 0, 0, 0}, 128, 56302480, 512 },
    { "dec.rb.5.c1.1.bias", 1, {128, 0, 0, 0}, 128, 56302992, 512 },
    { "dec.rb.5.c2.1.bias", 1, {128, 0, 0, 0}, 128, 56303504, 512 },
    { "dec.rb.5.c1.2.bias", 1, {128, 0, 0, 0}, 128, 56304016, 512 },
    { "dec.rb.5.c2.2.bias", 1, {128, 0, 0, 0}, 128, 56304528, 512 },
    { "dec.rb.6.c1.0.bias", 1, {64, 0, 0, 0}, 64, 56305040, 256 },
    { "dec.rb.6.c2.0.bias", 1, {64, 0, 0, 0}, 64, 56305296, 256 },
    { "dec.rb.6.c1.1.bias", 1, {64, 0, 0, 0}, 64, 56305552, 256 },
    { "dec.rb.6.c2.1.bias", 1, {64, 0, 0, 0}, 64, 56305808, 256 },
    { "dec.rb.6.c1.2.bias", 1, {64, 0, 0, 0}, 64, 56306064, 256 },
    { "dec.rb.6.c2.2.bias", 1, {64, 0, 0, 0}, 64, 56306320, 256 },
    { "dec.rb.7.c1.0.bias", 1, {64, 0, 0, 0}, 64, 56306576, 256 },
    { "dec.rb.7.c2.0.bias", 1, {64, 0, 0, 0}, 64, 56306832, 256 },
    { "dec.rb.7.c1.1.bias", 1, {64, 0, 0, 0}, 64, 56307088, 256 },
    { "dec.rb.7.c2.1.bias", 1, {64, 0, 0, 0}, 64, 56307344, 256 },
    { "dec.rb.7.c1.2.bias", 1, {64, 0, 0, 0}, 64, 56307600, 256 },
    { "dec.rb.7.c2.2.bias", 1, {64, 0, 0, 0}, 64, 56307856, 256 },
    { "dec.rb.8.c1.0.bias", 1, {64, 0, 0, 0}, 64, 56308112, 256 },
    { "dec.rb.8.c2.0.bias", 1, {64, 0, 0, 0}, 64, 56308368, 256 },
    { "dec.rb.8.c1.1.bias", 1, {64, 0, 0, 0}, 64, 56308624, 256 },
    { "dec.rb.8.c2.1.bias", 1, {64, 0, 0, 0}, 64, 56308880, 256 },
    { "dec.rb.8.c1.2.bias", 1, {64, 0, 0, 0}, 64, 56309136, 256 },
    { "dec.rb.8.c2.2.bias", 1, {64, 0, 0, 0}, 64, 56309392, 256 },
    { "dec.rb.9.c1.0.bias", 1, {32, 0, 0, 0}, 32, 56309648, 128 },
    { "dec.rb.9.c2.0.bias", 1, {32, 0, 0, 0}, 32, 56309776, 128 },
    { "dec.rb.9.c1.1.bias", 1, {32, 0, 0, 0}, 32, 56309904, 128 },
    { "dec.rb.9.c2.1.bias", 1, {32, 0, 0, 0}, 32, 56310032, 128 },
    { "dec.rb.9.c1.2.bias", 1, {32, 0, 0, 0}, 32, 56310160, 128 },
    { "dec.rb.9.c2.2.bias", 1, {32, 0, 0, 0}, 32, 56310288, 128 },
    { "dec.rb.10.c1.0.bias", 1, {32, 0, 0, 0}, 32, 56310416, 128 },
    { "dec.rb.10.c2.0.bias", 1, {32, 0, 0, 0}, 32, 56310544, 128 },
    { "dec.rb.10.c1.1.bias", 1, {32, 0, 0, 0}, 32, 56310672, 128 },
    { "dec.rb.10.c2.1.bias", 1, {32, 0, 0, 0}, 32, 56310800, 128 },
    { "dec.rb.10.c1.2.bias", 1, {32, 0, 0, 0}, 32, 56310928, 128 },
    { "dec.rb.10.c2.2.bias", 1, {32, 0, 0, 0}, 32, 56311056, 128 },
    { "dec.rb.11.c1.0.bias", 1, {32, 0, 0, 0}, 32, 56311184, 128 },
    { "dec.rb.11.c2.0.bias", 1, {32, 0, 0, 0}, 32, 56311312, 128 },
    { "dec.rb.11.c1.1.bias", 1, {32, 0, 0, 0}, 32, 56311440, 128 },
    { "dec.rb.11.c2.1.bias", 1, {32, 0, 0, 0}, 32, 56311568, 128 },
    { "dec.rb.11.c1.2.bias", 1, {32, 0, 0, 0}, 32, 56311696, 128 },
    { "dec.rb.11.c2.2.bias", 1, {32, 0, 0, 0}, 32, 56311824, 128 },
};

#define WTS_NUM_TENSORS  410

/* ── Section layout ── */
static const WtsSection wts_sections[] = {
    { "embed", &wts_tensors[0], 1, 8256, 48 },
    { "encoder.layer.0", &wts_tensors[1], 18, 1036416, 33072 },
    { "encoder.layer.1", &wts_tensors[19], 18, 1036416, 4178736 },
    { "encoder.layer.2", &wts_tensors[37], 18, 1036416, 8324400 },
    { "encoder.layer.3", &wts_tensors[55], 18, 1036416, 12470064 },
    { "encoder.layer.4", &wts_tensors[73], 18, 1036416, 16615728 },
    { "encoder.layer.5", &wts_tensors[91], 18, 1036416, 20761392 },
    { "encoder.project", &wts_tensors[109], 2, 74112, 24907056 },
    { "dp.main", &wts_tensors[111], 30, 189892, 25203504 },
    { "dp.flow.1", &wts_tensors[141], 28, 121757, 25963072 },
    { "dp.flow.2", &wts_tensors[169], 28, 121757, 26450100 },
    { "dp.flow.3", &wts_tensors[197], 28, 121757, 26937128 },
    { "dp.flow.4", &wts_tensors[225], 28, 121757, 27424156 },
    { "flow.0", &wts_tensors[253], 20, 1772640, 27911184 },
    { "flow.1", &wts_tensors[273], 20, 1772640, 35001744 },
    { "flow.2", &wts_tensors[293], 20, 1772640, 42092304 },
    { "flow.3", &wts_tensors[313], 20, 1772640, 49182864 },
    { "decoder", &wts_tensors[333], 77, 9632, 56273424 },
};

#define WTS_NUM_SECTIONS  18

/* ── Section indices ── */
#define WTS_SEC_EMBED  0
#define WTS_SEC_ENCODER_LAYER_0  1
#define WTS_SEC_ENCODER_LAYER_1  2
#define WTS_SEC_ENCODER_LAYER_2  3
#define WTS_SEC_ENCODER_LAYER_3  4
#define WTS_SEC_ENCODER_LAYER_4  5
#define WTS_SEC_ENCODER_LAYER_5  6
#define WTS_SEC_ENCODER_PROJECT  7
#define WTS_SEC_DP_MAIN  8
#define WTS_SEC_DP_FLOW_1  9
#define WTS_SEC_DP_FLOW_2  10
#define WTS_SEC_DP_FLOW_3  11
#define WTS_SEC_DP_FLOW_4  12
#define WTS_SEC_FLOW_0  13
#define WTS_SEC_FLOW_1  14
#define WTS_SEC_FLOW_2  15
#define WTS_SEC_FLOW_3  16
#define WTS_SEC_DECODER  17

/* ── Helper: get float pointer for a tensor ── */
static inline const float *wts_data(const unsigned char *base, const WtsTensor *t) {
    return (const float *)(base + t->offset);
}

/* ── Helper: get float pointer by index ── */
static inline const float *wts_data_at(const unsigned char *base, uint32_t idx) {
    return (const float *)(base + wts_tensors[idx].offset);
}

#endif /* MODEL_WEIGHTS_H */
