/* ============================================================
 * model_weights.h — Auto-generated by export_weights.py
 * Model: facebook/mms-tts-por (VITS, 36.3M params)
 * DO NOT EDIT MANUALLY — regenerate with:
 *   python export_weights.py --input model.safetensors \
 *       --output model.vtsm --header model_weights.h
 * ============================================================ */

#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

#include <stdint.h>
#include <stddef.h>

/* ── File header ── */
#define WTS_MAGIC            0x4D535456u  /* 'V','T','S','M' LE */
#define WTS_VERSION          2
#define WTS_VOCAB_SIZE       43
#define WTS_HIDDEN_SIZE      192
#define WTS_FILE_HEADER_SIZE 48
#define WTS_TOTAL_DATA_BYTES 56311904
#define WTS_QDATA_SIZE         14317792  /* int8 weight elements */
#define WTS_N_SCALES           9633  /* per-channel scales (float32) */
/* int8 qdata offset: WTS_FILE_HEADER_SIZE + WTS_TOTAL_DATA_BYTES */
/* scales offset:     WTS_FILE_HEADER_SIZE + WTS_TOTAL_DATA_BYTES + WTS_QDATA_SIZE */

/* ── Model dimensions ── */
#define WTS_NUM_HEADS        2
#define WTS_HEAD_DIM         96
#define WTS_NUM_LAYERS       6
#define WTS_REL_SIZE         9
#define WTS_FFN_DIM          768
#define WTS_FFN_KERNEL       3
#define WTS_HALF_FLOW        96
#define WTS_WAVE_KERNEL      5
#define WTS_NUM_WAVE         4
#define WTS_NUM_PRIOR_FLOWS  4
#define WTS_DP_BINS          10
#define WTS_DP_KERNEL        3
#define WTS_DP_NUM_FLOWS     4
#define WTS_DP_CHANNELS      2
#define WTS_DP_DDS_LAYERS    3
#define WTS_DP_PROJ_OUT      29
#define WTS_HIFI_INIT_CH     512
#define WTS_NUM_UP           4
#define WTS_RF_DILS          3
#define WTS_NUM_RESBLOCKS    12

/* ── Size constants (float32 element counts) ── */
#define WTS_EMBED_W_SIZE             8256

#define WTS_ENC_ATTN_W_SIZE          36864
#define WTS_ENC_ATTN_B_SIZE          192
#define WTS_ENC_REL_SIZE             864
#define WTS_ENC_FFN1_W_SIZE          442368
#define WTS_ENC_FFN1_B_SIZE          768
#define WTS_ENC_FFN2_W_SIZE          442368
#define WTS_ENC_FFN2_B_SIZE          192
#define WTS_ENC_LN_SIZE              192
#define WTS_ENC_LAYER_SIZE           1036416  /* per layer, all tensors */

#define WTS_ENC_PROJ_W_SIZE          73728
#define WTS_ENC_PROJ_B_SIZE          384

#define WTS_DP_CONV_PRE_W_SIZE       36864
#define WTS_DP_CONV_PRE_B_SIZE       192
#define WTS_DP_DDS_DW_W_SIZE         576
#define WTS_DP_DDS_DW_B_SIZE         192
#define WTS_DP_DDS_PW_W_SIZE         36864
#define WTS_DP_DDS_PW_B_SIZE         192
#define WTS_DP_DDS_NORM_SIZE         192
#define WTS_DP_DDS_LAYER_SIZE        38592  /* per DDS layer */
#define WTS_DP_DDS_SIZE              115776  /* full DDS block */
#define WTS_DP_CONV_PROJ_W_SIZE      36864
#define WTS_DP_CONV_PROJ_B_SIZE      192
#define WTS_DP_EA_SIZE               2  /* translate or log_scale */
#define WTS_DP_CF_PRE_W_SIZE         192
#define WTS_DP_CF_PRE_B_SIZE         192
#define WTS_DP_CF_PROJ_W_SIZE        5568
#define WTS_DP_CF_PROJ_B_SIZE        29

#define WTS_FLOW_PRE_W_SIZE          18432
#define WTS_FLOW_PRE_B_SIZE          192
#define WTS_FLOW_WN_IN_W_SIZE        368640
#define WTS_FLOW_WN_IN_B_SIZE        384
#define WTS_FLOW_WN_RS_W_SIZE        73728  /* layers 0-2 */
#define WTS_FLOW_WN_RS_W_SIZE_LAST   36864  /* layer 3 */
#define WTS_FLOW_WN_RS_B_SIZE        384
#define WTS_FLOW_WN_RS_B_SIZE_LAST   192
#define WTS_FLOW_POST_W_SIZE         18432
#define WTS_FLOW_POST_B_SIZE         96

#define WTS_DEC_PRE_W_SIZE           688128
#define WTS_DEC_PRE_B_SIZE           512
#define WTS_DEC_UP0_W_SIZE           2097152
#define WTS_DEC_UP0_B_SIZE           256
#define WTS_DEC_UP1_W_SIZE           524288
#define WTS_DEC_UP1_B_SIZE           128
#define WTS_DEC_UP2_W_SIZE           32768
#define WTS_DEC_UP2_B_SIZE           64
#define WTS_DEC_UP3_W_SIZE           8192
#define WTS_DEC_UP3_B_SIZE           32
#define WTS_DEC_RB0_0_W_SIZE        196608
#define WTS_DEC_RB0_0_B_SIZE        256
#define WTS_DEC_RB0_1_W_SIZE        458752
#define WTS_DEC_RB0_1_B_SIZE        256
#define WTS_DEC_RB0_2_W_SIZE        720896
#define WTS_DEC_RB0_2_B_SIZE        256
#define WTS_DEC_RB1_0_W_SIZE        49152
#define WTS_DEC_RB1_0_B_SIZE        128
#define WTS_DEC_RB1_1_W_SIZE        114688
#define WTS_DEC_RB1_1_B_SIZE        128
#define WTS_DEC_RB1_2_W_SIZE        180224
#define WTS_DEC_RB1_2_B_SIZE        128
#define WTS_DEC_RB2_0_W_SIZE        12288
#define WTS_DEC_RB2_0_B_SIZE        64
#define WTS_DEC_RB2_1_W_SIZE        28672
#define WTS_DEC_RB2_1_B_SIZE        64
#define WTS_DEC_RB2_2_W_SIZE        45056
#define WTS_DEC_RB2_2_B_SIZE        64
#define WTS_DEC_RB3_0_W_SIZE        3072
#define WTS_DEC_RB3_0_B_SIZE        32
#define WTS_DEC_RB3_1_W_SIZE        7168
#define WTS_DEC_RB3_1_B_SIZE        32
#define WTS_DEC_RB3_2_W_SIZE        11264
#define WTS_DEC_RB3_2_B_SIZE        32
#define WTS_DEC_POST_W_SIZE          224


/* ── Tensor descriptor ── */
typedef struct {
    const char *name;       /* tensor name */
    uint32_t     ndim;       /* number of dimensions */
    uint32_t     shape[4];   /* dimensions (0 if ndim < 4) */
    uint32_t     n_elements; /* total float32 count */
    uint64_t     offset;     /* byte offset in .vtsm file */
    uint64_t     size_bytes; /* n_elements * 4 */
} WtsTensor;

/* ── Section descriptor ── */
typedef struct {
    const char *name;             /* section name */
    const WtsTensor *tensors;     /* array of tensor descriptors */
    uint32_t     n_tensors;       /* number of tensors */
    uint32_t     n_elements;      /* total floats in section */
    uint64_t     offset;          /* byte offset of first tensor */
} WtsSection;

/* ── Flat tensor layout table (410 entries) ── */
static const WtsTensor wts_tensors[] = {
    { "embed_tokens.weight", 2, {43, 192, 0, 0}, 8256, 32, 33024 },
    { "enc.0.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 33056, 147456 },
    { "enc.0.q_proj.bias", 1, {192, 0, 0, 0}, 192, 180512, 768 },
    { "enc.0.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 181280, 147456 },
    { "enc.0.k_proj.bias", 1, {192, 0, 0, 0}, 192, 328736, 768 },
    { "enc.0.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 329504, 147456 },
    { "enc.0.v_proj.bias", 1, {192, 0, 0, 0}, 192, 476960, 768 },
    { "enc.0.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 477728, 147456 },
    { "enc.0.out_proj.bias", 1, {192, 0, 0, 0}, 192, 625184, 768 },
    { "enc.0.emb_rel_k", 2, {9, 96, 0, 0}, 864, 625952, 3456 },
    { "enc.0.emb_rel_v", 2, {9, 96, 0, 0}, 864, 629408, 3456 },
    { "enc.0.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 632864, 1769472 },
    { "enc.0.ffn1.bias", 1, {768, 0, 0, 0}, 768, 2402336, 3072 },
    { "enc.0.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 2405408, 1769472 },
    { "enc.0.ffn2.bias", 1, {192, 0, 0, 0}, 192, 4174880, 768 },
    { "enc.0.ln1.weight", 1, {192, 0, 0, 0}, 192, 4175648, 768 },
    { "enc.0.ln1.bias", 1, {192, 0, 0, 0}, 192, 4176416, 768 },
    { "enc.0.ln2.weight", 1, {192, 0, 0, 0}, 192, 4177184, 768 },
    { "enc.0.ln2.bias", 1, {192, 0, 0, 0}, 192, 4177952, 768 },
    { "enc.1.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 4178720, 147456 },
    { "enc.1.q_proj.bias", 1, {192, 0, 0, 0}, 192, 4326176, 768 },
    { "enc.1.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 4326944, 147456 },
    { "enc.1.k_proj.bias", 1, {192, 0, 0, 0}, 192, 4474400, 768 },
    { "enc.1.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 4475168, 147456 },
    { "enc.1.v_proj.bias", 1, {192, 0, 0, 0}, 192, 4622624, 768 },
    { "enc.1.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 4623392, 147456 },
    { "enc.1.out_proj.bias", 1, {192, 0, 0, 0}, 192, 4770848, 768 },
    { "enc.1.emb_rel_k", 2, {9, 96, 0, 0}, 864, 4771616, 3456 },
    { "enc.1.emb_rel_v", 2, {9, 96, 0, 0}, 864, 4775072, 3456 },
    { "enc.1.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 4778528, 1769472 },
    { "enc.1.ffn1.bias", 1, {768, 0, 0, 0}, 768, 6548000, 3072 },
    { "enc.1.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 6551072, 1769472 },
    { "enc.1.ffn2.bias", 1, {192, 0, 0, 0}, 192, 8320544, 768 },
    { "enc.1.ln1.weight", 1, {192, 0, 0, 0}, 192, 8321312, 768 },
    { "enc.1.ln1.bias", 1, {192, 0, 0, 0}, 192, 8322080, 768 },
    { "enc.1.ln2.weight", 1, {192, 0, 0, 0}, 192, 8322848, 768 },
    { "enc.1.ln2.bias", 1, {192, 0, 0, 0}, 192, 8323616, 768 },
    { "enc.2.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 8324384, 147456 },
    { "enc.2.q_proj.bias", 1, {192, 0, 0, 0}, 192, 8471840, 768 },
    { "enc.2.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 8472608, 147456 },
    { "enc.2.k_proj.bias", 1, {192, 0, 0, 0}, 192, 8620064, 768 },
    { "enc.2.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 8620832, 147456 },
    { "enc.2.v_proj.bias", 1, {192, 0, 0, 0}, 192, 8768288, 768 },
    { "enc.2.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 8769056, 147456 },
    { "enc.2.out_proj.bias", 1, {192, 0, 0, 0}, 192, 8916512, 768 },
    { "enc.2.emb_rel_k", 2, {9, 96, 0, 0}, 864, 8917280, 3456 },
    { "enc.2.emb_rel_v", 2, {9, 96, 0, 0}, 864, 8920736, 3456 },
    { "enc.2.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 8924192, 1769472 },
    { "enc.2.ffn1.bias", 1, {768, 0, 0, 0}, 768, 10693664, 3072 },
    { "enc.2.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 10696736, 1769472 },
    { "enc.2.ffn2.bias", 1, {192, 0, 0, 0}, 192, 12466208, 768 },
    { "enc.2.ln1.weight", 1, {192, 0, 0, 0}, 192, 12466976, 768 },
    { "enc.2.ln1.bias", 1, {192, 0, 0, 0}, 192, 12467744, 768 },
    { "enc.2.ln2.weight", 1, {192, 0, 0, 0}, 192, 12468512, 768 },
    { "enc.2.ln2.bias", 1, {192, 0, 0, 0}, 192, 12469280, 768 },
    { "enc.3.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 12470048, 147456 },
    { "enc.3.q_proj.bias", 1, {192, 0, 0, 0}, 192, 12617504, 768 },
    { "enc.3.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 12618272, 147456 },
    { "enc.3.k_proj.bias", 1, {192, 0, 0, 0}, 192, 12765728, 768 },
    { "enc.3.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 12766496, 147456 },
    { "enc.3.v_proj.bias", 1, {192, 0, 0, 0}, 192, 12913952, 768 },
    { "enc.3.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 12914720, 147456 },
    { "enc.3.out_proj.bias", 1, {192, 0, 0, 0}, 192, 13062176, 768 },
    { "enc.3.emb_rel_k", 2, {9, 96, 0, 0}, 864, 13062944, 3456 },
    { "enc.3.emb_rel_v", 2, {9, 96, 0, 0}, 864, 13066400, 3456 },
    { "enc.3.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 13069856, 1769472 },
    { "enc.3.ffn1.bias", 1, {768, 0, 0, 0}, 768, 14839328, 3072 },
    { "enc.3.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 14842400, 1769472 },
    { "enc.3.ffn2.bias", 1, {192, 0, 0, 0}, 192, 16611872, 768 },
    { "enc.3.ln1.weight", 1, {192, 0, 0, 0}, 192, 16612640, 768 },
    { "enc.3.ln1.bias", 1, {192, 0, 0, 0}, 192, 16613408, 768 },
    { "enc.3.ln2.weight", 1, {192, 0, 0, 0}, 192, 16614176, 768 },
    { "enc.3.ln2.bias", 1, {192, 0, 0, 0}, 192, 16614944, 768 },
    { "enc.4.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 16615712, 147456 },
    { "enc.4.q_proj.bias", 1, {192, 0, 0, 0}, 192, 16763168, 768 },
    { "enc.4.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 16763936, 147456 },
    { "enc.4.k_proj.bias", 1, {192, 0, 0, 0}, 192, 16911392, 768 },
    { "enc.4.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 16912160, 147456 },
    { "enc.4.v_proj.bias", 1, {192, 0, 0, 0}, 192, 17059616, 768 },
    { "enc.4.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 17060384, 147456 },
    { "enc.4.out_proj.bias", 1, {192, 0, 0, 0}, 192, 17207840, 768 },
    { "enc.4.emb_rel_k", 2, {9, 96, 0, 0}, 864, 17208608, 3456 },
    { "enc.4.emb_rel_v", 2, {9, 96, 0, 0}, 864, 17212064, 3456 },
    { "enc.4.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 17215520, 1769472 },
    { "enc.4.ffn1.bias", 1, {768, 0, 0, 0}, 768, 18984992, 3072 },
    { "enc.4.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 18988064, 1769472 },
    { "enc.4.ffn2.bias", 1, {192, 0, 0, 0}, 192, 20757536, 768 },
    { "enc.4.ln1.weight", 1, {192, 0, 0, 0}, 192, 20758304, 768 },
    { "enc.4.ln1.bias", 1, {192, 0, 0, 0}, 192, 20759072, 768 },
    { "enc.4.ln2.weight", 1, {192, 0, 0, 0}, 192, 20759840, 768 },
    { "enc.4.ln2.bias", 1, {192, 0, 0, 0}, 192, 20760608, 768 },
    { "enc.5.q_proj.weight", 2, {192, 192, 0, 0}, 36864, 20761376, 147456 },
    { "enc.5.q_proj.bias", 1, {192, 0, 0, 0}, 192, 20908832, 768 },
    { "enc.5.k_proj.weight", 2, {192, 192, 0, 0}, 36864, 20909600, 147456 },
    { "enc.5.k_proj.bias", 1, {192, 0, 0, 0}, 192, 21057056, 768 },
    { "enc.5.v_proj.weight", 2, {192, 192, 0, 0}, 36864, 21057824, 147456 },
    { "enc.5.v_proj.bias", 1, {192, 0, 0, 0}, 192, 21205280, 768 },
    { "enc.5.out_proj.weight", 2, {192, 192, 0, 0}, 36864, 21206048, 147456 },
    { "enc.5.out_proj.bias", 1, {192, 0, 0, 0}, 192, 21353504, 768 },
    { "enc.5.emb_rel_k", 2, {9, 96, 0, 0}, 864, 21354272, 3456 },
    { "enc.5.emb_rel_v", 2, {9, 96, 0, 0}, 864, 21357728, 3456 },
    { "enc.5.ffn1.weight", 3, {768, 192, 3, 0}, 442368, 21361184, 1769472 },
    { "enc.5.ffn1.bias", 1, {768, 0, 0, 0}, 768, 23130656, 3072 },
    { "enc.5.ffn2.weight", 3, {192, 768, 3, 0}, 442368, 23133728, 1769472 },
    { "enc.5.ffn2.bias", 1, {192, 0, 0, 0}, 192, 24903200, 768 },
    { "enc.5.ln1.weight", 1, {192, 0, 0, 0}, 192, 24903968, 768 },
    { "enc.5.ln1.bias", 1, {192, 0, 0, 0}, 192, 24904736, 768 },
    { "enc.5.ln2.weight", 1, {192, 0, 0, 0}, 192, 24905504, 768 },
    { "enc.5.ln2.bias", 1, {192, 0, 0, 0}, 192, 24906272, 768 },
    { "enc.proj.weight", 3, {384, 192, 1, 0}, 73728, 24907040, 294912 },
    { "enc.proj.bias", 1, {384, 0, 0, 0}, 384, 25201952, 1536 },
    { "dp.conv_pre.weight", 3, {192, 192, 1, 0}, 36864, 25203488, 147456 },
    { "dp.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 25350944, 768 },
    { "dp.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 25351712, 2304 },
    { "dp.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 25354016, 768 },
    { "dp.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 25354784, 147456 },
    { "dp.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 25502240, 768 },
    { "dp.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 25503008, 768 },
    { "dp.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 25503776, 768 },
    { "dp.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 25504544, 768 },
    { "dp.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 25505312, 768 },
    { "dp.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 25506080, 2304 },
    { "dp.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 25508384, 768 },
    { "dp.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 25509152, 147456 },
    { "dp.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 25656608, 768 },
    { "dp.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 25657376, 768 },
    { "dp.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 25658144, 768 },
    { "dp.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 25658912, 768 },
    { "dp.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 25659680, 768 },
    { "dp.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 25660448, 2304 },
    { "dp.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 25662752, 768 },
    { "dp.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 25663520, 147456 },
    { "dp.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 25810976, 768 },
    { "dp.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 25811744, 768 },
    { "dp.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 25812512, 768 },
    { "dp.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 25813280, 768 },
    { "dp.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 25814048, 768 },
    { "dp.conv_proj.weight", 3, {192, 192, 1, 0}, 36864, 25814816, 147456 },
    { "dp.conv_proj.bias", 1, {192, 0, 0, 0}, 192, 25962272, 768 },
    { "dp.flow0.translate", 1, {2, 0, 0, 0}, 2, 25963040, 8 },
    { "dp.flow0.log_scale", 1, {2, 0, 0, 0}, 2, 25963048, 8 },
    { "dp.flow1.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 25963056, 768 },
    { "dp.flow1.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 25963824, 768 },
    { "dp.flow1.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 25964592, 2304 },
    { "dp.flow1.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 25966896, 768 },
    { "dp.flow1.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 25967664, 147456 },
    { "dp.flow1.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 26115120, 768 },
    { "dp.flow1.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 26115888, 768 },
    { "dp.flow1.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 26116656, 768 },
    { "dp.flow1.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 26117424, 768 },
    { "dp.flow1.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 26118192, 768 },
    { "dp.flow1.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 26118960, 2304 },
    { "dp.flow1.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 26121264, 768 },
    { "dp.flow1.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 26122032, 147456 },
    { "dp.flow1.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 26269488, 768 },
    { "dp.flow1.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 26270256, 768 },
    { "dp.flow1.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 26271024, 768 },
    { "dp.flow1.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 26271792, 768 },
    { "dp.flow1.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 26272560, 768 },
    { "dp.flow1.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 26273328, 2304 },
    { "dp.flow1.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 26275632, 768 },
    { "dp.flow1.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 26276400, 147456 },
    { "dp.flow1.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 26423856, 768 },
    { "dp.flow1.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 26424624, 768 },
    { "dp.flow1.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 26425392, 768 },
    { "dp.flow1.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 26426160, 768 },
    { "dp.flow1.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 26426928, 768 },
    { "dp.flow1.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 26427696, 22272 },
    { "dp.flow1.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 26449968, 116 },
    { "dp.flow2.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 26450084, 768 },
    { "dp.flow2.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 26450852, 768 },
    { "dp.flow2.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 26451620, 2304 },
    { "dp.flow2.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 26453924, 768 },
    { "dp.flow2.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 26454692, 147456 },
    { "dp.flow2.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 26602148, 768 },
    { "dp.flow2.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 26602916, 768 },
    { "dp.flow2.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 26603684, 768 },
    { "dp.flow2.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 26604452, 768 },
    { "dp.flow2.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 26605220, 768 },
    { "dp.flow2.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 26605988, 2304 },
    { "dp.flow2.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 26608292, 768 },
    { "dp.flow2.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 26609060, 147456 },
    { "dp.flow2.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 26756516, 768 },
    { "dp.flow2.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 26757284, 768 },
    { "dp.flow2.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 26758052, 768 },
    { "dp.flow2.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 26758820, 768 },
    { "dp.flow2.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 26759588, 768 },
    { "dp.flow2.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 26760356, 2304 },
    { "dp.flow2.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 26762660, 768 },
    { "dp.flow2.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 26763428, 147456 },
    { "dp.flow2.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 26910884, 768 },
    { "dp.flow2.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 26911652, 768 },
    { "dp.flow2.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 26912420, 768 },
    { "dp.flow2.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 26913188, 768 },
    { "dp.flow2.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 26913956, 768 },
    { "dp.flow2.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 26914724, 22272 },
    { "dp.flow2.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 26936996, 116 },
    { "dp.flow3.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 26937112, 768 },
    { "dp.flow3.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 26937880, 768 },
    { "dp.flow3.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 26938648, 2304 },
    { "dp.flow3.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 26940952, 768 },
    { "dp.flow3.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 26941720, 147456 },
    { "dp.flow3.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 27089176, 768 },
    { "dp.flow3.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 27089944, 768 },
    { "dp.flow3.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 27090712, 768 },
    { "dp.flow3.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 27091480, 768 },
    { "dp.flow3.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 27092248, 768 },
    { "dp.flow3.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 27093016, 2304 },
    { "dp.flow3.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 27095320, 768 },
    { "dp.flow3.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 27096088, 147456 },
    { "dp.flow3.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 27243544, 768 },
    { "dp.flow3.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 27244312, 768 },
    { "dp.flow3.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 27245080, 768 },
    { "dp.flow3.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 27245848, 768 },
    { "dp.flow3.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 27246616, 768 },
    { "dp.flow3.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 27247384, 2304 },
    { "dp.flow3.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 27249688, 768 },
    { "dp.flow3.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 27250456, 147456 },
    { "dp.flow3.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 27397912, 768 },
    { "dp.flow3.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 27398680, 768 },
    { "dp.flow3.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 27399448, 768 },
    { "dp.flow3.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 27400216, 768 },
    { "dp.flow3.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 27400984, 768 },
    { "dp.flow3.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 27401752, 22272 },
    { "dp.flow3.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 27424024, 116 },
    { "dp.flow4.conv_pre.weight", 3, {192, 1, 1, 0}, 192, 27424140, 768 },
    { "dp.flow4.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 27424908, 768 },
    { "dp.flow4.dds.dw.0.weight", 3, {192, 1, 3, 0}, 576, 27425676, 2304 },
    { "dp.flow4.dds.dw.0.bias", 1, {192, 0, 0, 0}, 192, 27427980, 768 },
    { "dp.flow4.dds.pw.0.weight", 3, {192, 192, 1, 0}, 36864, 27428748, 147456 },
    { "dp.flow4.dds.pw.0.bias", 1, {192, 0, 0, 0}, 192, 27576204, 768 },
    { "dp.flow4.dds.n1.0.weight", 1, {192, 0, 0, 0}, 192, 27576972, 768 },
    { "dp.flow4.dds.n1.0.bias", 1, {192, 0, 0, 0}, 192, 27577740, 768 },
    { "dp.flow4.dds.n2.0.weight", 1, {192, 0, 0, 0}, 192, 27578508, 768 },
    { "dp.flow4.dds.n2.0.bias", 1, {192, 0, 0, 0}, 192, 27579276, 768 },
    { "dp.flow4.dds.dw.1.weight", 3, {192, 1, 3, 0}, 576, 27580044, 2304 },
    { "dp.flow4.dds.dw.1.bias", 1, {192, 0, 0, 0}, 192, 27582348, 768 },
    { "dp.flow4.dds.pw.1.weight", 3, {192, 192, 1, 0}, 36864, 27583116, 147456 },
    { "dp.flow4.dds.pw.1.bias", 1, {192, 0, 0, 0}, 192, 27730572, 768 },
    { "dp.flow4.dds.n1.1.weight", 1, {192, 0, 0, 0}, 192, 27731340, 768 },
    { "dp.flow4.dds.n1.1.bias", 1, {192, 0, 0, 0}, 192, 27732108, 768 },
    { "dp.flow4.dds.n2.1.weight", 1, {192, 0, 0, 0}, 192, 27732876, 768 },
    { "dp.flow4.dds.n2.1.bias", 1, {192, 0, 0, 0}, 192, 27733644, 768 },
    { "dp.flow4.dds.dw.2.weight", 3, {192, 1, 3, 0}, 576, 27734412, 2304 },
    { "dp.flow4.dds.dw.2.bias", 1, {192, 0, 0, 0}, 192, 27736716, 768 },
    { "dp.flow4.dds.pw.2.weight", 3, {192, 192, 1, 0}, 36864, 27737484, 147456 },
    { "dp.flow4.dds.pw.2.bias", 1, {192, 0, 0, 0}, 192, 27884940, 768 },
    { "dp.flow4.dds.n1.2.weight", 1, {192, 0, 0, 0}, 192, 27885708, 768 },
    { "dp.flow4.dds.n1.2.bias", 1, {192, 0, 0, 0}, 192, 27886476, 768 },
    { "dp.flow4.dds.n2.2.weight", 1, {192, 0, 0, 0}, 192, 27887244, 768 },
    { "dp.flow4.dds.n2.2.bias", 1, {192, 0, 0, 0}, 192, 27888012, 768 },
    { "dp.flow4.conv_proj.weight", 3, {29, 192, 1, 0}, 5568, 27888780, 22272 },
    { "dp.flow4.conv_proj.bias", 1, {29, 0, 0, 0}, 29, 27911052, 116 },
    { "flow.0.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 27911168, 73728 },
    { "flow.0.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 27984896, 768 },
    { "flow.0.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 27985664, 1474560 },
    { "flow.0.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 29460224, 1536 },
    { "flow.0.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 29461760, 294912 },
    { "flow.0.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 29756672, 1536 },
    { "flow.0.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 29758208, 1474560 },
    { "flow.0.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 31232768, 1536 },
    { "flow.0.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 31234304, 294912 },
    { "flow.0.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 31529216, 1536 },
    { "flow.0.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 31530752, 1474560 },
    { "flow.0.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 33005312, 1536 },
    { "flow.0.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 33006848, 294912 },
    { "flow.0.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 33301760, 1536 },
    { "flow.0.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 33303296, 1474560 },
    { "flow.0.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 34777856, 1536 },
    { "flow.0.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 34779392, 147456 },
    { "flow.0.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 34926848, 768 },
    { "flow.0.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 34927616, 73728 },
    { "flow.0.conv_post.bias", 1, {96, 0, 0, 0}, 96, 35001344, 384 },
    { "flow.1.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 35001728, 73728 },
    { "flow.1.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 35075456, 768 },
    { "flow.1.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 35076224, 1474560 },
    { "flow.1.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 36550784, 1536 },
    { "flow.1.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 36552320, 294912 },
    { "flow.1.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 36847232, 1536 },
    { "flow.1.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 36848768, 1474560 },
    { "flow.1.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 38323328, 1536 },
    { "flow.1.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 38324864, 294912 },
    { "flow.1.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 38619776, 1536 },
    { "flow.1.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 38621312, 1474560 },
    { "flow.1.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 40095872, 1536 },
    { "flow.1.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 40097408, 294912 },
    { "flow.1.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 40392320, 1536 },
    { "flow.1.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 40393856, 1474560 },
    { "flow.1.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 41868416, 1536 },
    { "flow.1.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 41869952, 147456 },
    { "flow.1.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 42017408, 768 },
    { "flow.1.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 42018176, 73728 },
    { "flow.1.conv_post.bias", 1, {96, 0, 0, 0}, 96, 42091904, 384 },
    { "flow.2.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 42092288, 73728 },
    { "flow.2.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 42166016, 768 },
    { "flow.2.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 42166784, 1474560 },
    { "flow.2.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 43641344, 1536 },
    { "flow.2.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 43642880, 294912 },
    { "flow.2.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 43937792, 1536 },
    { "flow.2.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 43939328, 1474560 },
    { "flow.2.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 45413888, 1536 },
    { "flow.2.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 45415424, 294912 },
    { "flow.2.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 45710336, 1536 },
    { "flow.2.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 45711872, 1474560 },
    { "flow.2.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 47186432, 1536 },
    { "flow.2.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 47187968, 294912 },
    { "flow.2.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 47482880, 1536 },
    { "flow.2.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 47484416, 1474560 },
    { "flow.2.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 48958976, 1536 },
    { "flow.2.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 48960512, 147456 },
    { "flow.2.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 49107968, 768 },
    { "flow.2.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 49108736, 73728 },
    { "flow.2.conv_post.bias", 1, {96, 0, 0, 0}, 96, 49182464, 384 },
    { "flow.3.conv_pre.weight", 3, {192, 96, 1, 0}, 18432, 49182848, 73728 },
    { "flow.3.conv_pre.bias", 1, {192, 0, 0, 0}, 192, 49256576, 768 },
    { "flow.3.wn.in.0.weight", 3, {384, 192, 5, 0}, 368640, 49257344, 1474560 },
    { "flow.3.wn.in.0.bias", 1, {384, 0, 0, 0}, 384, 50731904, 1536 },
    { "flow.3.wn.rs.0.weight", 3, {384, 192, 1, 0}, 73728, 50733440, 294912 },
    { "flow.3.wn.rs.0.bias", 1, {384, 0, 0, 0}, 384, 51028352, 1536 },
    { "flow.3.wn.in.1.weight", 3, {384, 192, 5, 0}, 368640, 51029888, 1474560 },
    { "flow.3.wn.in.1.bias", 1, {384, 0, 0, 0}, 384, 52504448, 1536 },
    { "flow.3.wn.rs.1.weight", 3, {384, 192, 1, 0}, 73728, 52505984, 294912 },
    { "flow.3.wn.rs.1.bias", 1, {384, 0, 0, 0}, 384, 52800896, 1536 },
    { "flow.3.wn.in.2.weight", 3, {384, 192, 5, 0}, 368640, 52802432, 1474560 },
    { "flow.3.wn.in.2.bias", 1, {384, 0, 0, 0}, 384, 54276992, 1536 },
    { "flow.3.wn.rs.2.weight", 3, {384, 192, 1, 0}, 73728, 54278528, 294912 },
    { "flow.3.wn.rs.2.bias", 1, {384, 0, 0, 0}, 384, 54573440, 1536 },
    { "flow.3.wn.in.3.weight", 3, {384, 192, 5, 0}, 368640, 54574976, 1474560 },
    { "flow.3.wn.in.3.bias", 1, {384, 0, 0, 0}, 384, 56049536, 1536 },
    { "flow.3.wn.rs.3.weight", 3, {192, 192, 1, 0}, 36864, 56051072, 147456 },
    { "flow.3.wn.rs.3.bias", 1, {192, 0, 0, 0}, 192, 56198528, 768 },
    { "flow.3.conv_post.weight", 3, {96, 192, 1, 0}, 18432, 56199296, 73728 },
    { "flow.3.conv_post.bias", 1, {96, 0, 0, 0}, 96, 56273024, 384 },
    { "dec.conv_pre.bias", 1, {512, 0, 0, 0}, 512, 56273408, 2048 },
    { "dec.up.0.bias", 1, {256, 0, 0, 0}, 256, 56275456, 1024 },
    { "dec.up.1.bias", 1, {128, 0, 0, 0}, 128, 56276480, 512 },
    { "dec.up.2.bias", 1, {64, 0, 0, 0}, 64, 56276992, 256 },
    { "dec.up.3.bias", 1, {32, 0, 0, 0}, 32, 56277248, 128 },
    { "dec.rb.0.c1.0.bias", 1, {256, 0, 0, 0}, 256, 56277376, 1024 },
    { "dec.rb.0.c2.0.bias", 1, {256, 0, 0, 0}, 256, 56278400, 1024 },
    { "dec.rb.0.c1.1.bias", 1, {256, 0, 0, 0}, 256, 56279424, 1024 },
    { "dec.rb.0.c2.1.bias", 1, {256, 0, 0, 0}, 256, 56280448, 1024 },
    { "dec.rb.0.c1.2.bias", 1, {256, 0, 0, 0}, 256, 56281472, 1024 },
    { "dec.rb.0.c2.2.bias", 1, {256, 0, 0, 0}, 256, 56282496, 1024 },
    { "dec.rb.1.c1.0.bias", 1, {256, 0, 0, 0}, 256, 56283520, 1024 },
    { "dec.rb.1.c2.0.bias", 1, {256, 0, 0, 0}, 256, 56284544, 1024 },
    { "dec.rb.1.c1.1.bias", 1, {256, 0, 0, 0}, 256, 56285568, 1024 },
    { "dec.rb.1.c2.1.bias", 1, {256, 0, 0, 0}, 256, 56286592, 1024 },
    { "dec.rb.1.c1.2.bias", 1, {256, 0, 0, 0}, 256, 56287616, 1024 },
    { "dec.rb.1.c2.2.bias", 1, {256, 0, 0, 0}, 256, 56288640, 1024 },
    { "dec.rb.2.c1.0.bias", 1, {256, 0, 0, 0}, 256, 56289664, 1024 },
    { "dec.rb.2.c2.0.bias", 1, {256, 0, 0, 0}, 256, 56290688, 1024 },
    { "dec.rb.2.c1.1.bias", 1, {256, 0, 0, 0}, 256, 56291712, 1024 },
    { "dec.rb.2.c2.1.bias", 1, {256, 0, 0, 0}, 256, 56292736, 1024 },
    { "dec.rb.2.c1.2.bias", 1, {256, 0, 0, 0}, 256, 56293760, 1024 },
    { "dec.rb.2.c2.2.bias", 1, {256, 0, 0, 0}, 256, 56294784, 1024 },
    { "dec.rb.3.c1.0.bias", 1, {128, 0, 0, 0}, 128, 56295808, 512 },
    { "dec.rb.3.c2.0.bias", 1, {128, 0, 0, 0}, 128, 56296320, 512 },
    { "dec.rb.3.c1.1.bias", 1, {128, 0, 0, 0}, 128, 56296832, 512 },
    { "dec.rb.3.c2.1.bias", 1, {128, 0, 0, 0}, 128, 56297344, 512 },
    { "dec.rb.3.c1.2.bias", 1, {128, 0, 0, 0}, 128, 56297856, 512 },
    { "dec.rb.3.c2.2.bias", 1, {128, 0, 0, 0}, 128, 56298368, 512 },
    { "dec.rb.4.c1.0.bias", 1, {128, 0, 0, 0}, 128, 56298880, 512 },
    { "dec.rb.4.c2.0.bias", 1, {128, 0, 0, 0}, 128, 56299392, 512 },
    { "dec.rb.4.c1.1.bias", 1, {128, 0, 0, 0}, 128, 56299904, 512 },
    { "dec.rb.4.c2.1.bias", 1, {128, 0, 0, 0}, 128, 56300416, 512 },
    { "dec.rb.4.c1.2.bias", 1, {128, 0, 0, 0}, 128, 56300928, 512 },
    { "dec.rb.4.c2.2.bias", 1, {128, 0, 0, 0}, 128, 56301440, 512 },
    { "dec.rb.5.c1.0.bias", 1, {128, 0, 0, 0}, 128, 56301952, 512 },
    { "dec.rb.5.c2.0.bias", 1, {128, 0, 0, 0}, 128, 56302464, 512 },
    { "dec.rb.5.c1.1.bias", 1, {128, 0, 0, 0}, 128, 56302976, 512 },
    { "dec.rb.5.c2.1.bias", 1, {128, 0, 0, 0}, 128, 56303488, 512 },
    { "dec.rb.5.c1.2.bias", 1, {128, 0, 0, 0}, 128, 56304000, 512 },
    { "dec.rb.5.c2.2.bias", 1, {128, 0, 0, 0}, 128, 56304512, 512 },
    { "dec.rb.6.c1.0.bias", 1, {64, 0, 0, 0}, 64, 56305024, 256 },
    { "dec.rb.6.c2.0.bias", 1, {64, 0, 0, 0}, 64, 56305280, 256 },
    { "dec.rb.6.c1.1.bias", 1, {64, 0, 0, 0}, 64, 56305536, 256 },
    { "dec.rb.6.c2.1.bias", 1, {64, 0, 0, 0}, 64, 56305792, 256 },
    { "dec.rb.6.c1.2.bias", 1, {64, 0, 0, 0}, 64, 56306048, 256 },
    { "dec.rb.6.c2.2.bias", 1, {64, 0, 0, 0}, 64, 56306304, 256 },
    { "dec.rb.7.c1.0.bias", 1, {64, 0, 0, 0}, 64, 56306560, 256 },
    { "dec.rb.7.c2.0.bias", 1, {64, 0, 0, 0}, 64, 56306816, 256 },
    { "dec.rb.7.c1.1.bias", 1, {64, 0, 0, 0}, 64, 56307072, 256 },
    { "dec.rb.7.c2.1.bias", 1, {64, 0, 0, 0}, 64, 56307328, 256 },
    { "dec.rb.7.c1.2.bias", 1, {64, 0, 0, 0}, 64, 56307584, 256 },
    { "dec.rb.7.c2.2.bias", 1, {64, 0, 0, 0}, 64, 56307840, 256 },
    { "dec.rb.8.c1.0.bias", 1, {64, 0, 0, 0}, 64, 56308096, 256 },
    { "dec.rb.8.c2.0.bias", 1, {64, 0, 0, 0}, 64, 56308352, 256 },
    { "dec.rb.8.c1.1.bias", 1, {64, 0, 0, 0}, 64, 56308608, 256 },
    { "dec.rb.8.c2.1.bias", 1, {64, 0, 0, 0}, 64, 56308864, 256 },
    { "dec.rb.8.c1.2.bias", 1, {64, 0, 0, 0}, 64, 56309120, 256 },
    { "dec.rb.8.c2.2.bias", 1, {64, 0, 0, 0}, 64, 56309376, 256 },
    { "dec.rb.9.c1.0.bias", 1, {32, 0, 0, 0}, 32, 56309632, 128 },
    { "dec.rb.9.c2.0.bias", 1, {32, 0, 0, 0}, 32, 56309760, 128 },
    { "dec.rb.9.c1.1.bias", 1, {32, 0, 0, 0}, 32, 56309888, 128 },
    { "dec.rb.9.c2.1.bias", 1, {32, 0, 0, 0}, 32, 56310016, 128 },
    { "dec.rb.9.c1.2.bias", 1, {32, 0, 0, 0}, 32, 56310144, 128 },
    { "dec.rb.9.c2.2.bias", 1, {32, 0, 0, 0}, 32, 56310272, 128 },
    { "dec.rb.10.c1.0.bias", 1, {32, 0, 0, 0}, 32, 56310400, 128 },
    { "dec.rb.10.c2.0.bias", 1, {32, 0, 0, 0}, 32, 56310528, 128 },
    { "dec.rb.10.c1.1.bias", 1, {32, 0, 0, 0}, 32, 56310656, 128 },
    { "dec.rb.10.c2.1.bias", 1, {32, 0, 0, 0}, 32, 56310784, 128 },
    { "dec.rb.10.c1.2.bias", 1, {32, 0, 0, 0}, 32, 56310912, 128 },
    { "dec.rb.10.c2.2.bias", 1, {32, 0, 0, 0}, 32, 56311040, 128 },
    { "dec.rb.11.c1.0.bias", 1, {32, 0, 0, 0}, 32, 56311168, 128 },
    { "dec.rb.11.c2.0.bias", 1, {32, 0, 0, 0}, 32, 56311296, 128 },
    { "dec.rb.11.c1.1.bias", 1, {32, 0, 0, 0}, 32, 56311424, 128 },
    { "dec.rb.11.c2.1.bias", 1, {32, 0, 0, 0}, 32, 56311552, 128 },
    { "dec.rb.11.c1.2.bias", 1, {32, 0, 0, 0}, 32, 56311680, 128 },
    { "dec.rb.11.c2.2.bias", 1, {32, 0, 0, 0}, 32, 56311808, 128 },
};

#define WTS_NUM_TENSORS  410

/* ── Section layout ── */
static const WtsSection wts_sections[] = {
    { "embed", &wts_tensors[0], 1, 8256, 32 },
    { "encoder.layer.0", &wts_tensors[1], 18, 1036416, 33056 },
    { "encoder.layer.1", &wts_tensors[19], 18, 1036416, 4178720 },
    { "encoder.layer.2", &wts_tensors[37], 18, 1036416, 8324384 },
    { "encoder.layer.3", &wts_tensors[55], 18, 1036416, 12470048 },
    { "encoder.layer.4", &wts_tensors[73], 18, 1036416, 16615712 },
    { "encoder.layer.5", &wts_tensors[91], 18, 1036416, 20761376 },
    { "encoder.project", &wts_tensors[109], 2, 74112, 24907040 },
    { "dp.main", &wts_tensors[111], 30, 189892, 25203488 },
    { "dp.flow.1", &wts_tensors[141], 28, 121757, 25963056 },
    { "dp.flow.2", &wts_tensors[169], 28, 121757, 26450084 },
    { "dp.flow.3", &wts_tensors[197], 28, 121757, 26937112 },
    { "dp.flow.4", &wts_tensors[225], 28, 121757, 27424140 },
    { "flow.0", &wts_tensors[253], 20, 1772640, 27911168 },
    { "flow.1", &wts_tensors[273], 20, 1772640, 35001728 },
    { "flow.2", &wts_tensors[293], 20, 1772640, 42092288 },
    { "flow.3", &wts_tensors[313], 20, 1772640, 49182848 },
    { "decoder", &wts_tensors[333], 77, 9632, 56273408 },
};

#define WTS_NUM_SECTIONS  18

/* ── Section indices ── */
#define WTS_SEC_EMBED  0
#define WTS_SEC_ENCODER_LAYER_0  1
#define WTS_SEC_ENCODER_LAYER_1  2
#define WTS_SEC_ENCODER_LAYER_2  3
#define WTS_SEC_ENCODER_LAYER_3  4
#define WTS_SEC_ENCODER_LAYER_4  5
#define WTS_SEC_ENCODER_LAYER_5  6
#define WTS_SEC_ENCODER_PROJECT  7
#define WTS_SEC_DP_MAIN  8
#define WTS_SEC_DP_FLOW_1  9
#define WTS_SEC_DP_FLOW_2  10
#define WTS_SEC_DP_FLOW_3  11
#define WTS_SEC_DP_FLOW_4  12
#define WTS_SEC_FLOW_0  13
#define WTS_SEC_FLOW_1  14
#define WTS_SEC_FLOW_2  15
#define WTS_SEC_FLOW_3  16
#define WTS_SEC_DECODER  17

/* ── Helper: get float pointer for a tensor ── */
static inline const float *wts_data(const unsigned char *base, const WtsTensor *t) {
    return (const float *)(base + t->offset);
}

/* ── Helper: get float pointer by index ── */
static inline const float *wts_data_at(const unsigned char *base, uint32_t idx) {
    return (const float *)(base + wts_tensors[idx].offset);
}

#endif /* MODEL_WEIGHTS_H */
