#include "vits.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* From model.c */
void set_dump_dir(const char *dir);

/* Default model path */
static const char *DEFAULT_MODEL = "model.vtsm";

/* ── Text chunking ──────────────────────────────────────────────────────
 * Splits text at sentence boundaries (. ? ! \n) into chunks of at most
 * MAX_TEXT_LEN characters. Each chunk is independently synthesizable. */

#define MAX_CHUNKS 16

static int split_text(const char *text, char (*chunks)[MAX_TEXT_LEN + 1], int *lens)
{
    int n = 0;
    size_t len = strlen(text);
    size_t pos = 0;

    while (pos < len && n < MAX_CHUNKS) {
        /* If remaining fits in one chunk, take it all */
        if (len - pos <= (size_t)MAX_TEXT_LEN) {
            size_t slen = len - pos;
            memcpy(chunks[n], text + pos, slen);
            chunks[n][slen] = '\0';
            lens[n] = (int)slen;
            n++;
            break;
        }

        /* Find a good break point: last sentence-ending char within limit */
        size_t limit = pos + (size_t)MAX_TEXT_LEN;
        size_t break_at = pos; /* fallback: hard cut */
        for (size_t i = pos; i < limit; i++) {
            if (text[i] == '.' || text[i] == '?' || text[i] == '!' || text[i] == '\n') {
                break_at = i + 1;
            }
        }
        /* If no sentence break found, break at last space */
        if (break_at == pos) {
            for (size_t i = limit; i > pos; i--) {
                if (text[i - 1] == ' ') {
                    break_at = i - 1;
                    break;
                }
            }
        }
        if (break_at == pos)
            break_at = limit; /* hard cut as last resort */

        size_t slen = break_at - pos;
        memcpy(chunks[n], text + pos, slen);
        chunks[n][slen] = '\0';
        lens[n] = (int)slen;
        n++;
        pos = break_at;
    }

    return n;
}

static const char *SAMPLE_TEXTS[] = {
    "Olá, mundo! Este é um exemplo de síntese de voz em português.",
    "A tecnologia de fala tem avançado rapidamente nos últimos anos.",
    "O modelo MMS foi desenvolvido pela Meta para suportar mais de mil línguas.",
};

static void print_usage(const char *prog)
{
    fprintf(stderr,
        "Usage: %s [options]\n"
        "\n"
        "Options:\n"
        "  --text TEXT       Text to synthesize\n"
        "  --output PATH     Output WAV path (default: output.wav)\n"
        "  --model PATH      Path to model (.vtsm, generated by export_weights.py)\n"
        "  --seed N          Random seed (default: 42, use -1 for random)\n"
        "  --multi           Synthesize all sample texts\n"
        "  --dump-dir DIR    Dump intermediate tensors for validation\n"
        "  --inject-dir DIR  Inject pre-generated latents from DIR (e.g. ref_out/)\n"
        "  --int8            Use INT8 + FP32 activations HiFi-GAN (default: Q16)\n"
        "  --help            Show this help\n"
        "\n"
        "Model: default is ./model.vtsm (generate with export_weights.py)\n"
        "\n"
        "Examples:\n"
        "  %s --text \"Olá, mundo!\"\n"
        "  %s --text \"Bom dia\" --output bom_dia.wav --seed -1\n"
        "  %s --text \"Olá, mundo!\" --inject-dir ./ref_out\n"
        "  %s --multi --dump-dir ./c_out\n"
        "  %s --text \"Olá, mundo!\" --int8 --output int8.wav\n",
        prog, prog, prog, prog, prog, prog);
}

int main(int argc, char **argv)
{
    const char *text = NULL;
    const char *output = "output.wav";
    const char *model_path = NULL;
    const char *dump_dir = NULL;
    const char *inject_dir = NULL;
    int seed = 42;
    int multi = 0;
    int use_q16 = 1;

    /* Parse args */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--text") == 0 && i + 1 < argc)
            text = argv[++i];
        else if (strcmp(argv[i], "--output") == 0 && i + 1 < argc)
            output = argv[++i];
        else if (strcmp(argv[i], "--model") == 0 && i + 1 < argc)
            model_path = argv[++i];
        else if (strcmp(argv[i], "--seed") == 0 && i + 1 < argc)
            seed = atoi(argv[++i]);
        else if (strcmp(argv[i], "--multi") == 0)
            multi = 1;
        else if (strcmp(argv[i], "--dump-dir") == 0 && i + 1 < argc)
            dump_dir = argv[++i];
        else if (strcmp(argv[i], "--inject-dir") == 0 && i + 1 < argc)
            inject_dir = argv[++i];
        else if (strcmp(argv[i], "--int8") == 0)
            use_q16 = 0;
        else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "Unknown argument: %s\n", argv[i]);
            print_usage(argv[0]);
            return 1;
        }
    }

    /* Default model */
    if (!model_path)
        model_path = DEFAULT_MODEL;

    /* Load model (small struct: ~6.4KB metadata, all weights in mmap) */
    VitsModel *model = (VitsModel *)calloc(1, sizeof(VitsModel));
    if (!model) {
        fprintf(stderr, "Error: out of memory\n");
        return 1;
    }
    Vocab vocab;
    vocab_init(&vocab);

    printf("Loading model: %s (vtsm) ...\n", model_path);
    int rc = load_vtsm(model_path, model, &vocab);
    if (rc != 0) {
        fprintf(stderr, "Error: failed to load model\n");
        free(model);
        return 1;
    }
    model->sampling_rate = SAMPLE_RATE;
    printf("  sampling rate: %d Hz\n", model->sampling_rate);

    if (dump_dir) {
        set_dump_dir(dump_dir);
#ifdef ENABLE_DUMP
        dp_set_dump_dir(dump_dir);
        flow_set_dump_dir(dump_dir);
        hifigan_q_set_dump_dir(dump_dir);
        hifigan_q16_set_dump_dir(dump_dir);
#endif
    }

    /* Initialize Q16 fixed-point pipeline if requested */
    if (use_q16) {
        if (hifigan_q16_init(&model->decoder_q16, &model->decoder_q) != 0) {
            fprintf(stderr, "Error: failed to initialize Q16 HiFi-GAN\n");
            free_model(model);
            free(model);
            return 1;
        }
        printf("  HiFi-GAN: Q16 fixed-point pipeline\n");
    } else {
        printf("  HiFi-GAN: INT8 + FP32 activations pipeline\n");
    }

    /* Determine texts and outputs */
    const char *texts[8];
    char outputs[8][512];
    int n_texts = 0;

    if (text) {
        texts[n_texts] = text;
        snprintf(outputs[n_texts], 512, "%s", output);
        n_texts++;
    } else if (multi) {
        for (int i = 0; i < 3 && i < 8; i++) {
            texts[n_texts] = SAMPLE_TEXTS[i];
            snprintf(outputs[n_texts], 512, "mms_por_%d.wav", i + 1);
            n_texts++;
        }
    } else {
        texts[n_texts] = SAMPLE_TEXTS[0];
        snprintf(outputs[n_texts], 512, "%s", output);
        n_texts++;
    }

    /* Synthesize all texts, then free weights, then write WAVs */
    float *waveforms[8] = {0};
    int wave_lens[8] = {0};
    int sample_rate = model->sampling_rate;

    for (int i = 0; i < n_texts; i++) {
        int text_len = (int)strlen(texts[i]);
        printf("[%d/%d] \"%s%s\" (%d chars)\n", i + 1, n_texts, texts[i],
               text_len > 60 ? "..." : "", text_len);

        int need_chunking = text_len > MAX_TEXT_LEN;
        char chunks[MAX_CHUNKS][MAX_TEXT_LEN + 1];
        int chunk_lens[MAX_CHUNKS];
        int n_chunks = 1;

        if (need_chunking) {
            n_chunks = split_text(texts[i], chunks, chunk_lens);
            if (n_chunks <= 0) {
                fprintf(stderr, "  Error: could not split text\n");
                for (int j = 0; j < i; j++) free(waveforms[j]);
                free_model(model);
                free(model);
                return 1;
            }
            printf("  split into %d chunks\n", n_chunks);
        } else {
            memcpy(chunks[0], texts[i], text_len + 1);
            chunk_lens[0] = text_len;
        }

        if (n_chunks == 1) {
            /* Single chunk: synthesize directly into output buffer */
            waveforms[i] = (float *)malloc(sizeof(float) * MAX_WAV_LEN);
            if (!waveforms[i]) {
                fprintf(stderr, "Error: out of memory\n");
                for (int j = 0; j < i; j++) free(waveforms[j]);
                free_model(model);
                free(model);
                return 1;
            }

            int rc = use_q16
                ? vits_synthesize_pipeline(model, &vocab, chunks[0], seed,
                                           inject_dir, waveforms[i], &wave_lens[i], 1)
                : vits_synthesize(model, &vocab, chunks[0], seed,
                                  inject_dir, waveforms[i], &wave_lens[i]);
            if (rc != 0) {
                fprintf(stderr, "  Error: synthesis failed\n");
                free(waveforms[i]);
                for (int j = 0; j < i; j++) free(waveforms[j]);
                free_model(model);
                free(model);
                return 1;
            }
        } else {
            /* Multiple chunks: synthesize each, then concatenate */
            waveforms[i] = (float *)malloc(sizeof(float) * MAX_WAV_LEN * n_chunks);
            if (!waveforms[i]) {
                fprintf(stderr, "Error: out of memory\n");
                for (int j = 0; j < i; j++) free(waveforms[j]);
                free_model(model);
                free(model);
                return 1;
            }
            wave_lens[i] = 0;

            float *tmp = (float *)malloc(sizeof(float) * MAX_WAV_LEN);
            if (!tmp) {
                fprintf(stderr, "Error: out of memory\n");
                free(waveforms[i]);
                for (int j = 0; j < i; j++) free(waveforms[j]);
                free_model(model);
                free(model);
                return 1;
            }

            for (int c = 0; c < n_chunks; c++) {
                int chunk_wave_len = 0;
                int rc = use_q16
                    ? vits_synthesize_pipeline(model, &vocab, chunks[c], seed,
                                               inject_dir, tmp, &chunk_wave_len, 1)
                    : vits_synthesize(model, &vocab, chunks[c], seed,
                                      inject_dir, tmp, &chunk_wave_len);
                if (rc != 0) {
                    fprintf(stderr, "  Error: synthesis failed (chunk %d)\n", c + 1);
                    free(tmp);
                    free(waveforms[i]);
                    for (int j = 0; j < i; j++) free(waveforms[j]);
                    free_model(model);
                    free(model);
                    return 1;
                }
                memcpy(waveforms[i] + wave_lens[i], tmp, chunk_wave_len * sizeof(float));
                wave_lens[i] += chunk_wave_len;
            }
            free(tmp);
        }

        double duration = (double)wave_lens[i] / sample_rate;
        printf("  -> %s (%.2fs)\n", outputs[i], duration);
    }

    /* Free Q16 params (heap-allocated), then model weights */
    if (model->decoder_q16.params)
        hifigan_q16_free(&model->decoder_q16);
    free_model(model);
    free(model);

    for (int i = 0; i < n_texts; i++) {
        if (write_wav16(outputs[i], waveforms[i], wave_lens[i], sample_rate) != 0) {
            fprintf(stderr, "  Error: failed to write %s\n", outputs[i]);
        }
        free(waveforms[i]);
    }

    printf("Done.\n");
    return 0;
}
