#include "vits.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* From model.c */
void set_dump_dir(const char *dir);

/* Default model path */
static const char *DEFAULT_MODEL = "model.vtsm";

static const char *SAMPLE_TEXTS[] = {
    "Olá, mundo! Este é um exemplo de síntese de voz em português.",
    "A tecnologia de fala tem avançado rapidamente nos últimos anos.",
    "O modelo MMS foi desenvolvido pela Meta para suportar mais de mil línguas.",
};

static void print_usage(const char *prog)
{
    fprintf(stderr,
        "Usage: %s [options]\n"
        "\n"
        "Options:\n"
        "  --text TEXT       Text to synthesize\n"
        "  --output PATH     Output WAV path (default: output.wav)\n"
        "  --model PATH      Path to model (.vtsm, generated by export_weights.py)\n"
        "  --seed N          Random seed (default: 42, use -1 for random)\n"
        "  --multi           Synthesize all sample texts\n"
        "  --dump-dir DIR    Dump intermediate tensors for validation\n"
        "  --inject-dir DIR  Inject pre-generated latents from DIR (e.g. ref_out/)\n"
        "  --hifi-int8       Use int8 quantized HiFi-GAN (per-channel)\n"
        "  --help            Show this help\n"
        "\n"
        "Model: default is ./model.vtsm (generate with export_weights.py)\n"
        "\n"
        "Examples:\n"
        "  %s --text \"Olá, mundo!\"\n"
        "  %s --text \"Bom dia\" --output bom_dia.wav --seed -1\n"
        "  %s --text \"Olá, mundo!\" --inject-dir ./ref_out\n"
        "  %s --multi --dump-dir ./c_out\n"
        "  %s --text \"Olá\" --hifi-int8 --dump-dir ./c_out_int8\n",
        prog, prog, prog, prog, prog, prog);
}

int main(int argc, char **argv)
{
    const char *text = NULL;
    const char *output = "output.wav";
    const char *model_path = NULL;
    const char *dump_dir = NULL;
    const char *inject_dir = NULL;
    int seed = 42;
    int multi = 0;
    int hifi_int8 = 0;

    /* Parse args */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--text") == 0 && i + 1 < argc)
            text = argv[++i];
        else if (strcmp(argv[i], "--output") == 0 && i + 1 < argc)
            output = argv[++i];
        else if (strcmp(argv[i], "--model") == 0 && i + 1 < argc)
            model_path = argv[++i];
        else if (strcmp(argv[i], "--seed") == 0 && i + 1 < argc)
            seed = atoi(argv[++i]);
        else if (strcmp(argv[i], "--multi") == 0)
            multi = 1;
        else if (strcmp(argv[i], "--dump-dir") == 0 && i + 1 < argc)
            dump_dir = argv[++i];
        else if (strcmp(argv[i], "--inject-dir") == 0 && i + 1 < argc)
            inject_dir = argv[++i];
        else if (strcmp(argv[i], "--hifi-int8") == 0)
            hifi_int8 = 1;
        else if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "Unknown argument: %s\n", argv[i]);
            print_usage(argv[0]);
            return 1;
        }
    }

    /* Default model */
    if (!model_path)
        model_path = DEFAULT_MODEL;

    /* Load model (small struct: ~6.4KB metadata, all weights in mmap) */
    VitsModel *model = (VitsModel *)calloc(1, sizeof(VitsModel));
    if (!model) {
        fprintf(stderr, "Error: out of memory\n");
        return 1;
    }
    Vocab vocab;
    vocab_init(&vocab);

    printf("Loading model: %s (vtsm) ...\n", model_path);
    int rc = load_vtsm(model_path, model, &vocab);
    if (rc != 0) {
        fprintf(stderr, "Error: failed to load model\n");
        free(model);
        return 1;
    }
    model->sampling_rate = SAMPLE_RATE;
    printf("  sampling rate: %d Hz\n", model->sampling_rate);

    /* Int8 HiFi-GAN: use pre-quantized from file (v2) or quantize at runtime (v1) */
    if (hifi_int8 && !model->use_int8_hifi) {
        printf("  quantizing HiFi-GAN to int8 (per-channel) ...\n");
        rc = hifigan_quantize(&model->decoder, &model->decoder_q);
        if (rc != 0) {
            fprintf(stderr, "  Error: int8 quantization failed\n");
            free_model(model);
            free(model);
            return 1;
        }
        model->use_int8_hifi = 1;
        printf("  int8 size: %.1f MB (scales: %d entries)\n",
               (model->decoder_q.qdata_size) / (1024.0 * 1024.0),
               model->decoder_q.n_scales);
    }

    if (dump_dir) {
        set_dump_dir(dump_dir);
#ifdef ENABLE_DUMP
        dp_set_dump_dir(dump_dir);
        flow_set_dump_dir(dump_dir);
        hifigan_set_dump_dir(dump_dir);
        if (hifi_int8) hifigan_q_set_dump_dir(dump_dir);
#endif
    }

    /* Determine texts and outputs */
    const char *texts[8];
    char outputs[8][512];
    int n_texts = 0;

    if (text) {
        texts[n_texts] = text;
        snprintf(outputs[n_texts], 512, "%s", output);
        n_texts++;
    } else if (multi) {
        for (int i = 0; i < 3 && i < 8; i++) {
            texts[n_texts] = SAMPLE_TEXTS[i];
            snprintf(outputs[n_texts], 512, "mms_por_%d.wav", i + 1);
            n_texts++;
        }
    } else {
        texts[n_texts] = SAMPLE_TEXTS[0];
        snprintf(outputs[n_texts], 512, "%s", output);
        n_texts++;
    }

    /* Synthesize all texts, then free weights, then write WAVs */
    float *waveforms[8] = {0};
    int wave_lens[8] = {0};
    int sample_rate = model->sampling_rate;

    for (int i = 0; i < n_texts; i++) {
        int display_len = (int)strlen(texts[i]);
        if (display_len > 60) display_len = 60;
        printf("[%d/%d] \"%s%s\"\n", i + 1, n_texts, texts[i],
               (int)strlen(texts[i]) > 60 ? "..." : "");

        waveforms[i] = (float *)malloc(sizeof(float) * MAX_WAV_LEN);
        if (!waveforms[i]) {
            fprintf(stderr, "Error: out of memory\n");
            for (int j = 0; j < i; j++) free(waveforms[j]);
            free_model(model);
            free(model);
            return 1;
        }

        if (vits_synthesize(model, &vocab, texts[i], seed, inject_dir, waveforms[i], &wave_lens[i]) != 0) {
            fprintf(stderr, "  Error: synthesis failed\n");
            free(waveforms[i]);
            for (int j = 0; j < i; j++) free(waveforms[j]);
            free_model(model);
            free(model);
            return 1;
        }

        double duration = (double)wave_lens[i] / sample_rate;
        printf("  -> %s (%.2fs)\n", outputs[i], duration);
    }

    /* Free model weights before writing WAVs to minimize peak memory */
    free_model(model);
    free(model);

    for (int i = 0; i < n_texts; i++) {
        if (write_wav16(outputs[i], waveforms[i], wave_lens[i], sample_rate) != 0) {
            fprintf(stderr, "  Error: failed to write %s\n", outputs[i]);
        }
        free(waveforms[i]);
    }

    printf("Done.\n");
    return 0;
}
